# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fomconguimain.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1173, 895)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setWindowOpacity(0.0)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_fotf_viewer = QtWidgets.QWidget()
        self.tab_fotf_viewer.setObjectName("tab_fotf_viewer")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_fotf_viewer)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_fotf_viewer)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(395, 468))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.bottonBode_2 = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.bottonBode_2.setFont(font)
        self.bottonBode_2.setObjectName("bottonBode_2")
        self.verticalLayout_7.addWidget(self.bottonBode_2)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_7.addWidget(self.comboBox)
        self.verticalLayout_5.addLayout(self.verticalLayout_7)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_5.addWidget(self.pushButton_7)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_8.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_fotf_viewer)
        self.groupBox_3.setMinimumSize(QtCore.QSize(395, 468))
        self.groupBox_3.setMaximumSize(QtCore.QSize(395, 468))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 43, 375, 423))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setObjectName("formLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_2)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_Freq = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.groupBox_Freq.setFont(font)
        self.groupBox_Freq.setObjectName("groupBox_Freq")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_Freq)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_Freq)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setIconSize(QtCore.QSize(10, 10))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 0, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_Freq)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 0, 1, 1, 1)
        self.bottonBode = QtWidgets.QPushButton(self.groupBox_Freq)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.bottonBode.setFont(font)
        self.bottonBode.setObjectName("bottonBode")
        self.gridLayout.addWidget(self.bottonBode, 1, 0, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_4.addWidget(self.groupBox_Freq)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonTime = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.buttonTime.setFont(font)
        self.buttonTime.setObjectName("buttonTime")
        self.gridLayout_2.addWidget(self.buttonTime, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.buttonInputVector = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.buttonInputVector.setFont(font)
        self.buttonInputVector.setObjectName("buttonInputVector")
        self.gridLayout_2.addWidget(self.buttonInputVector, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.comboBoxtimeType = QtWidgets.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxtimeType.setFont(font)
        self.comboBoxtimeType.setEditable(False)
        self.comboBoxtimeType.setCurrentText("")
        self.comboBoxtimeType.setMaxVisibleItems(2)
        self.comboBoxtimeType.setModelColumn(0)
        self.comboBoxtimeType.setObjectName("comboBoxtimeType")
        self.gridLayout_2.addWidget(self.comboBoxtimeType, 2, 1, 1, 1)
        self.buttonsimulate = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.buttonsimulate.setFont(font)
        self.buttonsimulate.setObjectName("buttonsimulate")
        self.gridLayout_2.addWidget(self.buttonsimulate, 3, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_8.addWidget(self.groupBox_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_fotf_viewer)
        self.textBrowser.setMinimumSize(QtCore.QSize(711, 731))
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_3.addWidget(self.textBrowser)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab_fotf_viewer, "")
        self.tabFotfid = QtWidgets.QWidget()
        self.tabFotfid.setObjectName("tabFotfid")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tabFotfid)
        self.groupBox_7.setGeometry(QtCore.QRect(290, 10, 620, 761))
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_13.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_13.setSpacing(5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(600, 250))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_10.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_10.setSpacing(5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setHorizontalSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_StartFreq = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_StartFreq.setObjectName("lineEdit_StartFreq")
        self.gridLayout_3.addWidget(self.lineEdit_StartFreq, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_3.addWidget(self.comboBox_2, 0, 1, 1, 4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(70, 40))
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 3, 1, 1)
        self.lineEdit_StopFreq = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_StopFreq.setObjectName("lineEdit_StopFreq")
        self.gridLayout_3.addWidget(self.lineEdit_StopFreq, 1, 2, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_3)
        self.verticalLayout_13.addWidget(self.groupBox_2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_5.setMaximumSize(QtCore.QSize(700, 250))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_3.setMaximumSize(QtCore.QSize(500, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_5.addWidget(self.comboBox_3)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_8.setMaximumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_5.addWidget(self.pushButton_8)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setMinimumSize(QtCore.QSize(250, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.horizontalLayout_6.addWidget(self.comboBox_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(65, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_4.addWidget(self.lineEdit_7)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.verticalLayout_13.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_12.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBoxNumerator = QtWidgets.QCheckBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBoxNumerator.setFont(font)
        self.checkBoxNumerator.setObjectName("checkBoxNumerator")
        self.horizontalLayout_9.addWidget(self.checkBoxNumerator)
        self.plainTextEdit_Zeros = QtWidgets.QPlainTextEdit(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.plainTextEdit_Zeros.setFont(font)
        self.plainTextEdit_Zeros.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.plainTextEdit_Zeros.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plainTextEdit_Zeros.setCenterOnScroll(True)
        self.plainTextEdit_Zeros.setObjectName("plainTextEdit_Zeros")
        self.horizontalLayout_9.addWidget(self.plainTextEdit_Zeros)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_Denominator = QtWidgets.QCheckBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_Denominator.setFont(font)
        self.checkBox_Denominator.setObjectName("checkBox_Denominator")
        self.horizontalLayout_8.addWidget(self.checkBox_Denominator)
        self.plainTextEdit_Poles = QtWidgets.QPlainTextEdit(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plainTextEdit_Poles.setFont(font)
        self.plainTextEdit_Poles.setObjectName("plainTextEdit_Poles")
        self.horizontalLayout_8.addWidget(self.plainTextEdit_Poles)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_Denominator_2 = QtWidgets.QCheckBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_Denominator_2.setFont(font)
        self.checkBox_Denominator_2.setObjectName("checkBox_Denominator_2")
        self.horizontalLayout_7.addWidget(self.checkBox_Denominator_2)
        self.lineEdit_Delay = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_Delay.setMaximumSize(QtCore.QSize(71, 39))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_Delay.setFont(font)
        self.lineEdit_Delay.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Delay.setObjectName("lineEdit_Delay")
        self.horizontalLayout_7.addWidget(self.lineEdit_Delay)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.verticalLayout_13.addWidget(self.groupBox_6)
        self.groupBoxInitialGuess = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBoxInitialGuess.setObjectName("groupBoxInitialGuess")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBoxInitialGuess)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.groupBoxInitialGuess)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMaximumSize(QtCore.QSize(90, 601))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBoxInitialGuess)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(45, 50))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_10.addWidget(self.lineEdit_3)
        self.label_7 = QtWidgets.QLabel(self.groupBoxInitialGuess)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMaximumSize(QtCore.QSize(60, 601))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBoxInitialGuess)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setPlaceholderText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_10.addWidget(self.lineEdit_6)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBoxInitialGuess)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.horizontalLayout_10.addWidget(self.comboBox_5)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBoxInitialGuess)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_10.addWidget(self.pushButton_9)
        self.verticalLayout_13.addWidget(self.groupBoxInitialGuess)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_Denominator_3 = QtWidgets.QCheckBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Denominator_3.sizePolicy().hasHeightForWidth())
        self.checkBox_Denominator_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_Denominator_3.setFont(font)
        self.checkBox_Denominator_3.setObjectName("checkBox_Denominator_3")
        self.gridLayout_4.addWidget(self.checkBox_Denominator_3, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMaximumSize(QtCore.QSize(110, 601))
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 1, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setPlaceholderText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_4.addWidget(self.lineEdit_8, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMaximumSize(QtCore.QSize(110, 601))
        self.label_13.setTextFormat(QtCore.Qt.RichText)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 3, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_9.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setPlaceholderText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_4.addWidget(self.lineEdit_9, 0, 4, 1, 1)
        self.checkBox_Denominator_4 = QtWidgets.QCheckBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Denominator_4.sizePolicy().hasHeightForWidth())
        self.checkBox_Denominator_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_Denominator_4.setFont(font)
        self.checkBox_Denominator_4.setObjectName("checkBox_Denominator_4")
        self.gridLayout_4.addWidget(self.checkBox_Denominator_4, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMaximumSize(QtCore.QSize(110, 601))
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 1, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_11.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11.setPlaceholderText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_4.addWidget(self.lineEdit_11, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMaximumSize(QtCore.QSize(110, 601))
        self.label_12.setTextFormat(QtCore.Qt.RichText)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 3, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setPlaceholderText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_4.addWidget(self.lineEdit_10, 1, 4, 1, 1)
        self.verticalLayout_13.addLayout(self.gridLayout_4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_6.setObjectName("comboBox_6")
        self.horizontalLayout_11.addWidget(self.comboBox_6)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_11.addWidget(self.pushButton_10)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.tabWidget.addTab(self.tabFotfid, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1173, 21))
        self.menubar.setObjectName("menubar")
        self.menuImport = QtWidgets.QMenu(self.menubar)
        self.menuImport.setObjectName("menuImport")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        self.menuModel = QtWidgets.QMenu(self.menubar)
        self.menuModel.setObjectName("menuModel")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionStability_Check = QtWidgets.QAction(MainWindow)
        self.actionStability_Check.setObjectName("actionStability_Check")
        self.actionValidate = QtWidgets.QAction(MainWindow)
        self.actionValidate.setEnabled(False)
        self.actionValidate.setObjectName("actionValidate")
        self.actionTime_Domain_Data = QtWidgets.QAction(MainWindow)
        self.actionTime_Domain_Data.setObjectName("actionTime_Domain_Data")
        self.actionInitial_Guess_Model = QtWidgets.QAction(MainWindow)
        self.actionInitial_Guess_Model.setObjectName("actionInitial_Guess_Model")
        self.menuImport.addSeparator()
        self.menuImport.addSeparator()
        self.menuImport.addAction(self.actionTime_Domain_Data)
        self.menuImport.addSeparator()
        self.menuImport.addAction(self.actionInitial_Guess_Model)
        self.menuData.addSeparator()
        self.menuModel.addSeparator()
        self.menuModel.addAction(self.actionStability_Check)
        self.menuModel.addSeparator()
        self.menuModel.addAction(self.actionValidate)
        self.menubar.addAction(self.menuImport.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuModel.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.comboBoxtimeType.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FOMCON Python"))
        self.groupBox_4.setTitle(_translate("MainWindow", "FO Transfer Functions"))
        self.pushButton_3.setText(_translate("MainWindow", "Add"))
        self.pushButton_4.setText(_translate("MainWindow", "Edit"))
        self.pushButton_6.setText(_translate("MainWindow", "Delete"))
        self.bottonBode_2.setText(_translate("MainWindow", "Refresh List"))
        self.pushButton_7.setText(_translate("MainWindow", "Get Oustaloop Model"))
        self.groupBox_3.setTitle(_translate("MainWindow", "System Analysis"))
        self.pushButton.setText(_translate("MainWindow", "View in console"))
        self.pushButton_2.setText(_translate("MainWindow", "Stability test"))
        self.groupBox_Freq.setTitle(_translate("MainWindow", "Frequency Domain"))
        self.pushButton_5.setText(_translate("MainWindow", "Freq Range"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "rad/s"))
        self.bottonBode.setText(_translate("MainWindow", "Bode Plot"))
        self.groupBox.setTitle(_translate("MainWindow", "Time Domain"))
        self.buttonTime.setText(_translate("MainWindow", "Time Vector"))
        self.lineEdit.setText(_translate("MainWindow", "0:0.1:30"))
        self.buttonInputVector.setText(_translate("MainWindow", "Input Vector"))
        self.lineEdit_2.setText(_translate("MainWindow", "1*ones(0,300)"))
        self.buttonsimulate.setText(_translate("MainWindow", "Simulate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_fotf_viewer), _translate("MainWindow", "FOTF Viewer"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Identification and Options"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Simulation Parameter"))
        self.lineEdit_StartFreq.setText(_translate("MainWindow", "0.0001"))
        self.lineEdit_StartFreq.setPlaceholderText(_translate("MainWindow", "Start (float)"))
        self.label_2.setText(_translate("MainWindow", "w range:"))
        self.lineEdit_5.setText(_translate("MainWindow", "10"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "(int)"))
        self.label.setText(_translate("MainWindow", "Method:"))
        self.label_3.setText(_translate("MainWindow", "Order:"))
        self.lineEdit_StopFreq.setText(_translate("MainWindow", "10000"))
        self.lineEdit_StopFreq.setPlaceholderText(_translate("MainWindow", "Stop (int)"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Source Data"))
        self.label_4.setText(_translate("MainWindow", "DATA Objects:"))
        self.pushButton_8.setText(_translate("MainWindow", "Refresh"))
        self.label_5.setText(_translate("MainWindow", "Algorithm:      "))
        self.label_6.setText(_translate("MainWindow", "Lamda:"))
        self.lineEdit_7.setText(_translate("MainWindow", "0.01"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Identified Model"))
        self.checkBoxNumerator.setText(_translate("MainWindow", "fix"))
        self.plainTextEdit_Zeros.setStatusTip(_translate("MainWindow", "0"))
        self.plainTextEdit_Zeros.setPlaceholderText(_translate("MainWindow", "Zeros"))
        self.checkBox_Denominator.setText(_translate("MainWindow", "fix"))
        self.plainTextEdit_Poles.setPlaceholderText(_translate("MainWindow", "Poles"))
        self.checkBox_Denominator_2.setText(_translate("MainWindow", "delay [s] :"))
        self.lineEdit_Delay.setText(_translate("MainWindow", "0"))
        self.lineEdit_Delay.setPlaceholderText(_translate("MainWindow", "int [s]"))
        self.groupBoxInitialGuess.setTitle(_translate("MainWindow", "Generate Initial Guess Model"))
        self.label_8.setText(_translate("MainWindow", "q[0.01:2):"))
        self.lineEdit_3.setText(_translate("MainWindow", "0.5"))
        self.label_7.setText(_translate("MainWindow", "Order:"))
        self.lineEdit_6.setText(_translate("MainWindow", "4"))
        self.pushButton_9.setText(_translate("MainWindow", "Generate"))
        self.checkBox_Denominator_3.setText(_translate("MainWindow", "Co-efficients"))
        self.label_9.setText(_translate("MainWindow", "Minimum:"))
        self.lineEdit_8.setText(_translate("MainWindow", "4"))
        self.label_13.setText(_translate("MainWindow", "Maximum:"))
        self.lineEdit_9.setText(_translate("MainWindow", "4"))
        self.checkBox_Denominator_4.setText(_translate("MainWindow", "Exponents"))
        self.label_10.setText(_translate("MainWindow", "Minimum:"))
        self.lineEdit_11.setText(_translate("MainWindow", "4"))
        self.label_12.setText(_translate("MainWindow", "Maximum:"))
        self.lineEdit_10.setText(_translate("MainWindow", "4"))
        self.pushButton_10.setText(_translate("MainWindow", "Identify"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFotfid), _translate("MainWindow", "FOTF Identification"))
        self.menuImport.setTitle(_translate("MainWindow", "Import"))
        self.menuData.setTitle(_translate("MainWindow", "Data"))
        self.menuModel.setTitle(_translate("MainWindow", "Model"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionStability_Check.setText(_translate("MainWindow", "Stability Check"))
        self.actionValidate.setText(_translate("MainWindow", "Validate"))
        self.actionTime_Domain_Data.setText(_translate("MainWindow", "Time Domain Data"))
        self.actionInitial_Guess_Model.setText(_translate("MainWindow", "Initial Guess Model"))

