# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\CompSys\4th Semeter THESIS\Code\fomcon\fomconguimainnew.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(683, 835)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setWindowOpacity(0.0)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_fotf_viewer = QtWidgets.QWidget()
        self.tab_fotf_viewer.setObjectName("tab_fotf_viewer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_fotf_viewer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_fotf_viewer)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_EditFOTF = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.pushButton_EditFOTF.setFont(font)
        self.pushButton_EditFOTF.setObjectName("pushButton_EditFOTF")
        self.gridLayout_5.addWidget(self.pushButton_EditFOTF, 0, 1, 1, 1)
        self.comboBoxFOTF = QtWidgets.QComboBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxFOTF.setFont(font)
        self.comboBoxFOTF.setObjectName("comboBoxFOTF")
        self.gridLayout_5.addWidget(self.comboBoxFOTF, 1, 0, 2, 3)
        self.pushButton_AddFotf = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.pushButton_AddFotf.setFont(font)
        self.pushButton_AddFotf.setObjectName("pushButton_AddFotf")
        self.gridLayout_5.addWidget(self.pushButton_AddFotf, 0, 0, 1, 1)
        self.pushButton_DeleteFOTF = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.pushButton_DeleteFOTF.setFont(font)
        self.pushButton_DeleteFOTF.setObjectName("pushButton_DeleteFOTF")
        self.gridLayout_5.addWidget(self.pushButton_DeleteFOTF, 0, 2, 1, 1)
        self.pushBottonRefresh = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushBottonRefresh.setFont(font)
        self.pushBottonRefresh.setObjectName("pushBottonRefresh")
        self.gridLayout_5.addWidget(self.pushBottonRefresh, 3, 0, 1, 1)
        self.pushButton_GetOustaloop = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.pushButton_GetOustaloop.setFont(font)
        self.pushButton_GetOustaloop.setObjectName("pushButton_GetOustaloop")
        self.gridLayout_5.addWidget(self.pushButton_GetOustaloop, 3, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_fotf_viewer)
        self.groupBox_3.setMinimumSize(QtCore.QSize(395, 468))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_Freq = QtWidgets.QGroupBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.groupBox_Freq.setFont(font)
        self.groupBox_Freq.setObjectName("groupBox_Freq")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_Freq)
        self.gridLayout.setObjectName("gridLayout")
        self.label_21 = QtWidgets.QLabel(self.groupBox_Freq)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_Freq)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 0, 0, 1, 1)
        self.bottonBodePlot = QtWidgets.QPushButton(self.groupBox_Freq)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.bottonBodePlot.setFont(font)
        self.bottonBodePlot.setObjectName("bottonBodePlot")
        self.gridLayout.addWidget(self.bottonBodePlot, 2, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_Freq)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 2, 1, 1)
        self.lineEdit_HigehrFreq = QtWidgets.QLineEdit(self.groupBox_Freq)
        self.lineEdit_HigehrFreq.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_HigehrFreq.setFont(font)
        self.lineEdit_HigehrFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_HigehrFreq.setObjectName("lineEdit_HigehrFreq")
        self.gridLayout.addWidget(self.lineEdit_HigehrFreq, 1, 1, 1, 1)
        self.pushButton_StabilityTest = QtWidgets.QPushButton(self.groupBox_Freq)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_StabilityTest.setFont(font)
        self.pushButton_StabilityTest.setObjectName("pushButton_StabilityTest")
        self.gridLayout.addWidget(self.pushButton_StabilityTest, 2, 1, 1, 1)
        self.pushButtonViewInConsole = QtWidgets.QPushButton(self.groupBox_Freq)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonViewInConsole.setFont(font)
        self.pushButtonViewInConsole.setObjectName("pushButtonViewInConsole")
        self.gridLayout.addWidget(self.pushButtonViewInConsole, 2, 0, 1, 1)
        self.lineEdit_FreqDataPoints = QtWidgets.QLineEdit(self.groupBox_Freq)
        self.lineEdit_FreqDataPoints.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_FreqDataPoints.setFont(font)
        self.lineEdit_FreqDataPoints.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_FreqDataPoints.setObjectName("lineEdit_FreqDataPoints")
        self.gridLayout.addWidget(self.lineEdit_FreqDataPoints, 1, 2, 1, 1)
        self.lineEdit_LowerFreq = QtWidgets.QLineEdit(self.groupBox_Freq)
        self.lineEdit_LowerFreq.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_LowerFreq.setFont(font)
        self.lineEdit_LowerFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_LowerFreq.setObjectName("lineEdit_LowerFreq")
        self.gridLayout.addWidget(self.lineEdit_LowerFreq, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_Freq)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 2, 1, 1)
        self.lineEdit_StartTime = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_StartTime.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_StartTime.setFont(font)
        self.lineEdit_StartTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_StartTime.setObjectName("lineEdit_StartTime")
        self.gridLayout_2.addWidget(self.lineEdit_StartTime, 1, 0, 1, 1)
        self.lineEdit_StepTime = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_StepTime.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_StepTime.setFont(font)
        self.lineEdit_StepTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_StepTime.setObjectName("lineEdit_StepTime")
        self.gridLayout_2.addWidget(self.lineEdit_StepTime, 1, 1, 1, 1)
        self.lineEdit_StopTime = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_StopTime.sizePolicy().hasHeightForWidth())
        self.lineEdit_StopTime.setSizePolicy(sizePolicy)
        self.lineEdit_StopTime.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_StopTime.setFont(font)
        self.lineEdit_StopTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_StopTime.setObjectName("lineEdit_StopTime")
        self.gridLayout_2.addWidget(self.lineEdit_StopTime, 1, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 2, 0, 1, 1)
        self.label_TimeVector = QtWidgets.QLabel(self.groupBox)
        self.label_TimeVector.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_TimeVector.setFont(font)
        self.label_TimeVector.setAlignment(QtCore.Qt.AlignCenter)
        self.label_TimeVector.setObjectName("label_TimeVector")
        self.gridLayout_2.addWidget(self.label_TimeVector, 2, 1, 1, 1)
        self.comboBoxtimeType = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxtimeType.sizePolicy().hasHeightForWidth())
        self.comboBoxtimeType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxtimeType.setFont(font)
        self.comboBoxtimeType.setEditable(False)
        self.comboBoxtimeType.setCurrentText("")
        self.comboBoxtimeType.setMaxVisibleItems(2)
        self.comboBoxtimeType.setModelColumn(0)
        self.comboBoxtimeType.setObjectName("comboBoxtimeType")
        self.gridLayout_2.addWidget(self.comboBoxtimeType, 2, 2, 1, 1)
        self.lineEdit_inputTime = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_inputTime.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_inputTime.setFont(font)
        self.lineEdit_inputTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_inputTime.setObjectName("lineEdit_inputTime")
        self.gridLayout_2.addWidget(self.lineEdit_inputTime, 3, 0, 1, 1)
        self.lineEdit_TimeVextorDisplay = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_TimeVextorDisplay.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_TimeVextorDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_TimeVextorDisplay.setReadOnly(True)
        self.lineEdit_TimeVextorDisplay.setObjectName("lineEdit_TimeVextorDisplay")
        self.gridLayout_2.addWidget(self.lineEdit_TimeVextorDisplay, 3, 1, 1, 1)
        self.buttoSimulate = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttoSimulate.sizePolicy().hasHeightForWidth())
        self.buttoSimulate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.buttoSimulate.setFont(font)
        self.buttoSimulate.setObjectName("buttoSimulate")
        self.gridLayout_2.addWidget(self.buttoSimulate, 3, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tab_fotf_viewer, "")
        self.tabFotfid = QtWidgets.QWidget()
        self.tabFotfid.setObjectName("tabFotfid")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tabFotfid)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabFotfid)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_10.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_10.setSpacing(5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setHorizontalSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_StartFreq = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_StartFreq.setFont(font)
        self.lineEdit_StartFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_StartFreq.setObjectName("lineEdit_StartFreq")
        self.gridLayout_3.addWidget(self.lineEdit_StartFreq, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_3.addWidget(self.comboBox_2, 0, 1, 1, 4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(70, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 3, 1, 1)
        self.lineEdit_StopFreq = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_StopFreq.setFont(font)
        self.lineEdit_StopFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_StopFreq.setObjectName("lineEdit_StopFreq")
        self.gridLayout_3.addWidget(self.lineEdit_StopFreq, 1, 2, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_3)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tabFotfid)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_5.addWidget(self.comboBox_3)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_5.addWidget(self.pushButton_8)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setMinimumSize(QtCore.QSize(250, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.horizontalLayout_6.addWidget(self.comboBox_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(65, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(70, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_4.addWidget(self.lineEdit_7)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.verticalLayout_13.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_12.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBoxNumerator = QtWidgets.QCheckBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxNumerator.setFont(font)
        self.checkBoxNumerator.setObjectName("checkBoxNumerator")
        self.horizontalLayout_9.addWidget(self.checkBoxNumerator)
        self.plainTextEdit_Zeros = QtWidgets.QPlainTextEdit(self.groupBox_6)
        self.plainTextEdit_Zeros.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.plainTextEdit_Zeros.setFont(font)
        self.plainTextEdit_Zeros.setAccessibleDescription("")
        self.plainTextEdit_Zeros.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.plainTextEdit_Zeros.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plainTextEdit_Zeros.setCenterOnScroll(True)
        self.plainTextEdit_Zeros.setObjectName("plainTextEdit_Zeros")
        self.horizontalLayout_9.addWidget(self.plainTextEdit_Zeros)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_Denominator = QtWidgets.QCheckBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Denominator.setFont(font)
        self.checkBox_Denominator.setObjectName("checkBox_Denominator")
        self.horizontalLayout_8.addWidget(self.checkBox_Denominator)
        self.plainTextEdit_Poles = QtWidgets.QPlainTextEdit(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_Poles.setFont(font)
        self.plainTextEdit_Poles.setObjectName("plainTextEdit_Poles")
        self.horizontalLayout_8.addWidget(self.plainTextEdit_Poles)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_Denominator_2 = QtWidgets.QCheckBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Denominator_2.setFont(font)
        self.checkBox_Denominator_2.setObjectName("checkBox_Denominator_2")
        self.horizontalLayout_7.addWidget(self.checkBox_Denominator_2)
        self.lineEdit_Delay = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_Delay.setMaximumSize(QtCore.QSize(71, 39))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Delay.setFont(font)
        self.lineEdit_Delay.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Delay.setObjectName("lineEdit_Delay")
        self.horizontalLayout_7.addWidget(self.lineEdit_Delay)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.verticalLayout_13.addWidget(self.groupBox_6)
        self.groupBoxInitialGuess = QtWidgets.QGroupBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxInitialGuess.setFont(font)
        self.groupBoxInitialGuess.setObjectName("groupBoxInitialGuess")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBoxInitialGuess)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.groupBoxInitialGuess)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMaximumSize(QtCore.QSize(90, 601))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBoxInitialGuess)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(45, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_10.addWidget(self.lineEdit_3)
        self.label_7 = QtWidgets.QLabel(self.groupBoxInitialGuess)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMaximumSize(QtCore.QSize(60, 601))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBoxInitialGuess)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setPlaceholderText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_10.addWidget(self.lineEdit_6)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBoxInitialGuess)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.horizontalLayout_10.addWidget(self.comboBox_5)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBoxInitialGuess)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_10.addWidget(self.pushButton_9)
        self.verticalLayout_13.addWidget(self.groupBoxInitialGuess)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_Denominator_3 = QtWidgets.QCheckBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Denominator_3.sizePolicy().hasHeightForWidth())
        self.checkBox_Denominator_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Denominator_3.setFont(font)
        self.checkBox_Denominator_3.setObjectName("checkBox_Denominator_3")
        self.gridLayout_4.addWidget(self.checkBox_Denominator_3, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMaximumSize(QtCore.QSize(110, 601))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 1, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setPlaceholderText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_4.addWidget(self.lineEdit_8, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMaximumSize(QtCore.QSize(110, 601))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setTextFormat(QtCore.Qt.RichText)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 3, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_9.sizePolicy().hasHeightForWidth())
        self.lineEdit_9.setSizePolicy(sizePolicy)
        self.lineEdit_9.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setPlaceholderText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_4.addWidget(self.lineEdit_9, 0, 4, 1, 1)
        self.checkBox_Denominator_4 = QtWidgets.QCheckBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Denominator_4.sizePolicy().hasHeightForWidth())
        self.checkBox_Denominator_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Denominator_4.setFont(font)
        self.checkBox_Denominator_4.setObjectName("checkBox_Denominator_4")
        self.gridLayout_4.addWidget(self.checkBox_Denominator_4, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMaximumSize(QtCore.QSize(110, 601))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 1, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_11.sizePolicy().hasHeightForWidth())
        self.lineEdit_11.setSizePolicy(sizePolicy)
        self.lineEdit_11.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11.setPlaceholderText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_4.addWidget(self.lineEdit_11, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMaximumSize(QtCore.QSize(110, 601))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setTextFormat(QtCore.Qt.RichText)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 3, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_10.sizePolicy().hasHeightForWidth())
        self.lineEdit_10.setSizePolicy(sizePolicy)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setPlaceholderText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_4.addWidget(self.lineEdit_10, 1, 4, 1, 1)
        self.verticalLayout_13.addLayout(self.gridLayout_4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_6.sizePolicy().hasHeightForWidth())
        self.comboBox_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName("comboBox_6")
        self.horizontalLayout_11.addWidget(self.comboBox_6)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_11.addWidget(self.pushButton_10)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.verticalLayout_9.addWidget(self.groupBox_7)
        self.tabWidget.addTab(self.tabFotfid, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 683, 21))
        self.menubar.setObjectName("menubar")
        self.menuImport = QtWidgets.QMenu(self.menubar)
        self.menuImport.setObjectName("menuImport")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        self.menuModel = QtWidgets.QMenu(self.menubar)
        self.menuModel.setObjectName("menuModel")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionStability_Check = QtWidgets.QAction(MainWindow)
        self.actionStability_Check.setObjectName("actionStability_Check")
        self.actionValidate = QtWidgets.QAction(MainWindow)
        self.actionValidate.setEnabled(False)
        self.actionValidate.setObjectName("actionValidate")
        self.actionTime_Domain_Data = QtWidgets.QAction(MainWindow)
        self.actionTime_Domain_Data.setObjectName("actionTime_Domain_Data")
        self.actionInitial_Guess_Model = QtWidgets.QAction(MainWindow)
        self.actionInitial_Guess_Model.setObjectName("actionInitial_Guess_Model")
        self.menuImport.addSeparator()
        self.menuImport.addSeparator()
        self.menuImport.addAction(self.actionTime_Domain_Data)
        self.menuImport.addSeparator()
        self.menuImport.addAction(self.actionInitial_Guess_Model)
        self.menuData.addSeparator()
        self.menuModel.addSeparator()
        self.menuModel.addAction(self.actionStability_Check)
        self.menuModel.addSeparator()
        self.menuModel.addAction(self.actionValidate)
        self.menubar.addAction(self.menuImport.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuModel.menuAction())
        self.label_21.setBuddy(self.lineEdit_HigehrFreq)
        self.label_19.setBuddy(self.lineEdit_LowerFreq)
        self.label_20.setBuddy(self.lineEdit_FreqDataPoints)
        self.label_16.setBuddy(self.lineEdit_StartTime)
        self.label_17.setBuddy(self.lineEdit_StepTime)
        self.label_18.setBuddy(self.lineEdit_StopTime)
        self.label_22.setBuddy(self.lineEdit_inputTime)
        self.label_3.setBuddy(self.lineEdit_5)
        self.label_6.setBuddy(self.lineEdit_7)
        self.label_8.setBuddy(self.lineEdit_3)
        self.label_7.setBuddy(self.lineEdit_6)
        self.label_9.setBuddy(self.lineEdit_8)
        self.label_13.setBuddy(self.lineEdit_9)
        self.label_10.setBuddy(self.lineEdit_11)
        self.label_12.setBuddy(self.lineEdit_10)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.comboBoxtimeType.setCurrentIndex(-1)
        self.tabWidget.tabBarClicked['int'].connect(self.comboBoxFOTF.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.pushButton_AddFotf)
        MainWindow.setTabOrder(self.pushButton_AddFotf, self.pushButton_EditFOTF)
        MainWindow.setTabOrder(self.pushButton_EditFOTF, self.pushButton_DeleteFOTF)
        MainWindow.setTabOrder(self.pushButton_DeleteFOTF, self.comboBoxFOTF)
        MainWindow.setTabOrder(self.comboBoxFOTF, self.pushBottonRefresh)
        MainWindow.setTabOrder(self.pushBottonRefresh, self.pushButton_GetOustaloop)
        MainWindow.setTabOrder(self.pushButton_GetOustaloop, self.lineEdit_LowerFreq)
        MainWindow.setTabOrder(self.lineEdit_LowerFreq, self.lineEdit_HigehrFreq)
        MainWindow.setTabOrder(self.lineEdit_HigehrFreq, self.lineEdit_FreqDataPoints)
        MainWindow.setTabOrder(self.lineEdit_FreqDataPoints, self.pushButtonViewInConsole)
        MainWindow.setTabOrder(self.pushButtonViewInConsole, self.pushButton_StabilityTest)
        MainWindow.setTabOrder(self.pushButton_StabilityTest, self.bottonBodePlot)
        MainWindow.setTabOrder(self.bottonBodePlot, self.lineEdit_StartTime)
        MainWindow.setTabOrder(self.lineEdit_StartTime, self.lineEdit_StepTime)
        MainWindow.setTabOrder(self.lineEdit_StepTime, self.lineEdit_StopTime)
        MainWindow.setTabOrder(self.lineEdit_StopTime, self.comboBoxtimeType)
        MainWindow.setTabOrder(self.comboBoxtimeType, self.lineEdit_inputTime)
        MainWindow.setTabOrder(self.lineEdit_inputTime, self.lineEdit_TimeVextorDisplay)
        MainWindow.setTabOrder(self.lineEdit_TimeVextorDisplay, self.buttoSimulate)
        MainWindow.setTabOrder(self.buttoSimulate, self.comboBox_2)
        MainWindow.setTabOrder(self.comboBox_2, self.lineEdit_StartFreq)
        MainWindow.setTabOrder(self.lineEdit_StartFreq, self.lineEdit_StopFreq)
        MainWindow.setTabOrder(self.lineEdit_StopFreq, self.lineEdit_5)
        MainWindow.setTabOrder(self.lineEdit_5, self.comboBox_3)
        MainWindow.setTabOrder(self.comboBox_3, self.pushButton_8)
        MainWindow.setTabOrder(self.pushButton_8, self.comboBox_4)
        MainWindow.setTabOrder(self.comboBox_4, self.lineEdit_7)
        MainWindow.setTabOrder(self.lineEdit_7, self.checkBoxNumerator)
        MainWindow.setTabOrder(self.checkBoxNumerator, self.plainTextEdit_Zeros)
        MainWindow.setTabOrder(self.plainTextEdit_Zeros, self.checkBox_Denominator)
        MainWindow.setTabOrder(self.checkBox_Denominator, self.plainTextEdit_Poles)
        MainWindow.setTabOrder(self.plainTextEdit_Poles, self.checkBox_Denominator_2)
        MainWindow.setTabOrder(self.checkBox_Denominator_2, self.lineEdit_Delay)
        MainWindow.setTabOrder(self.lineEdit_Delay, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.lineEdit_6)
        MainWindow.setTabOrder(self.lineEdit_6, self.comboBox_5)
        MainWindow.setTabOrder(self.comboBox_5, self.pushButton_9)
        MainWindow.setTabOrder(self.pushButton_9, self.checkBox_Denominator_3)
        MainWindow.setTabOrder(self.checkBox_Denominator_3, self.lineEdit_8)
        MainWindow.setTabOrder(self.lineEdit_8, self.lineEdit_9)
        MainWindow.setTabOrder(self.lineEdit_9, self.checkBox_Denominator_4)
        MainWindow.setTabOrder(self.checkBox_Denominator_4, self.lineEdit_11)
        MainWindow.setTabOrder(self.lineEdit_11, self.lineEdit_10)
        MainWindow.setTabOrder(self.lineEdit_10, self.comboBox_6)
        MainWindow.setTabOrder(self.comboBox_6, self.pushButton_10)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FOMCON Python"))
        self.tabWidget.setToolTip(_translate("MainWindow", "Fractional Order Transfer Function Time Domain Identification"))
        self.groupBox_4.setTitle(_translate("MainWindow", "FO Transfer Functions"))
        self.pushButton_EditFOTF.setText(_translate("MainWindow", "Edit"))
        self.pushButton_AddFotf.setText(_translate("MainWindow", "Add"))
        self.pushButton_DeleteFOTF.setText(_translate("MainWindow", "Delete"))
        self.pushBottonRefresh.setText(_translate("MainWindow", "Refresh List"))
        self.pushButton_GetOustaloop.setText(_translate("MainWindow", "Get Oustaloop Model"))
        self.groupBox_3.setTitle(_translate("MainWindow", "System Analysis"))
        self.groupBox_Freq.setTitle(_translate("MainWindow", "Frequency Domain"))
        self.label_21.setText(_translate("MainWindow", "Higher Freq (rad/s):"))
        self.label_19.setText(_translate("MainWindow", "Lower freq (rad/s):"))
        self.bottonBodePlot.setText(_translate("MainWindow", "Bode Plot"))
        self.label_20.setText(_translate("MainWindow", "Data points (int):"))
        self.lineEdit_HigehrFreq.setText(_translate("MainWindow", "1000"))
        self.pushButton_StabilityTest.setText(_translate("MainWindow", "Stability test"))
        self.pushButtonViewInConsole.setText(_translate("MainWindow", "View in console"))
        self.lineEdit_FreqDataPoints.setText(_translate("MainWindow", "5000"))
        self.lineEdit_LowerFreq.setText(_translate("MainWindow", "0.001"))
        self.groupBox.setTitle(_translate("MainWindow", "Time Domain"))
        self.label_16.setText(_translate("MainWindow", "Start (s):"))
        self.label_17.setText(_translate("MainWindow", "Step (s):"))
        self.label_18.setText(_translate("MainWindow", "Stop (s):"))
        self.lineEdit_StartTime.setText(_translate("MainWindow", "0"))
        self.lineEdit_StepTime.setText(_translate("MainWindow", "0.1"))
        self.lineEdit_StopTime.setText(_translate("MainWindow", "30"))
        self.label_22.setText(_translate("MainWindow", "Input:"))
        self.label_TimeVector.setText(_translate("MainWindow", "TimeVector:"))
        self.lineEdit_inputTime.setText(_translate("MainWindow", "1"))
        self.buttoSimulate.setText(_translate("MainWindow", "Simulate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_fotf_viewer), _translate("MainWindow", "FOTF Viewer"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Simulation Parameter"))
        self.lineEdit_StartFreq.setText(_translate("MainWindow", "0.0001"))
        self.lineEdit_StartFreq.setPlaceholderText(_translate("MainWindow", "Start (float)"))
        self.label_2.setText(_translate("MainWindow", "w range:"))
        self.lineEdit_5.setText(_translate("MainWindow", "10"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "(int)"))
        self.label.setText(_translate("MainWindow", "Method:"))
        self.label_3.setText(_translate("MainWindow", "Order:"))
        self.lineEdit_StopFreq.setText(_translate("MainWindow", "10000"))
        self.lineEdit_StopFreq.setPlaceholderText(_translate("MainWindow", "Stop (int)"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Identification and Options"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Source Data"))
        self.label_4.setText(_translate("MainWindow", "DATA Objects:"))
        self.pushButton_8.setText(_translate("MainWindow", "Refresh"))
        self.label_5.setText(_translate("MainWindow", "Algorithm:      "))
        self.label_6.setText(_translate("MainWindow", "Lamda:"))
        self.lineEdit_7.setText(_translate("MainWindow", "0.01"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Identified Model"))
        self.checkBoxNumerator.setText(_translate("MainWindow", "fix"))
        self.plainTextEdit_Zeros.setStatusTip(_translate("MainWindow", "0"))
        self.plainTextEdit_Zeros.setPlaceholderText(_translate("MainWindow", "Zeros"))
        self.checkBox_Denominator.setText(_translate("MainWindow", "fix"))
        self.plainTextEdit_Poles.setPlaceholderText(_translate("MainWindow", "Poles"))
        self.checkBox_Denominator_2.setText(_translate("MainWindow", "delay [s] :"))
        self.lineEdit_Delay.setText(_translate("MainWindow", "0"))
        self.lineEdit_Delay.setPlaceholderText(_translate("MainWindow", "int [s]"))
        self.groupBoxInitialGuess.setTitle(_translate("MainWindow", "Generate Initial Guess Model"))
        self.label_8.setText(_translate("MainWindow", "q[0.01:2):"))
        self.lineEdit_3.setText(_translate("MainWindow", "0.5"))
        self.label_7.setText(_translate("MainWindow", "Order:"))
        self.lineEdit_6.setText(_translate("MainWindow", "4"))
        self.pushButton_9.setText(_translate("MainWindow", "Generate"))
        self.checkBox_Denominator_3.setText(_translate("MainWindow", "Co-efficients"))
        self.label_9.setText(_translate("MainWindow", "Minimum:"))
        self.lineEdit_8.setText(_translate("MainWindow", "4"))
        self.label_13.setText(_translate("MainWindow", "Maximum:"))
        self.lineEdit_9.setText(_translate("MainWindow", "4"))
        self.checkBox_Denominator_4.setText(_translate("MainWindow", "Exponents"))
        self.label_10.setText(_translate("MainWindow", "Minimum:"))
        self.lineEdit_11.setText(_translate("MainWindow", "4"))
        self.label_12.setText(_translate("MainWindow", "Maximum:"))
        self.lineEdit_10.setText(_translate("MainWindow", "4"))
        self.pushButton_10.setText(_translate("MainWindow", "Identify"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFotfid), _translate("MainWindow", "FOTF Identification"))
        self.menuImport.setTitle(_translate("MainWindow", "Import"))
        self.menuData.setTitle(_translate("MainWindow", "Data"))
        self.menuModel.setTitle(_translate("MainWindow", "Model"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionStability_Check.setText(_translate("MainWindow", "Stability Check"))
        self.actionValidate.setText(_translate("MainWindow", "Validate"))
        self.actionTime_Domain_Data.setText(_translate("MainWindow", "Time Domain Data"))
        self.actionInitial_Guess_Model.setText(_translate("MainWindow", "Initial Guess Model"))

