# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(468, 474)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_10 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_10.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_EditFOTF_2 = QtWidgets.QPushButton(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.pushButton_EditFOTF_2.setFont(font)
        self.pushButton_EditFOTF_2.setObjectName("pushButton_EditFOTF_2")
        self.gridLayout_8.addWidget(self.pushButton_EditFOTF_2, 0, 1, 1, 1)
        self.comboBoxFOTF_2 = QtWidgets.QComboBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxFOTF_2.setFont(font)
        self.comboBoxFOTF_2.setObjectName("comboBoxFOTF_2")
        self.gridLayout_8.addWidget(self.comboBoxFOTF_2, 1, 0, 2, 3)
        self.pushButton_AddFotf_2 = QtWidgets.QPushButton(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.pushButton_AddFotf_2.setFont(font)
        self.pushButton_AddFotf_2.setObjectName("pushButton_AddFotf_2")
        self.gridLayout_8.addWidget(self.pushButton_AddFotf_2, 0, 0, 1, 1)
        self.pushButton_DeleteFOTF_2 = QtWidgets.QPushButton(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.pushButton_DeleteFOTF_2.setFont(font)
        self.pushButton_DeleteFOTF_2.setObjectName("pushButton_DeleteFOTF_2")
        self.gridLayout_8.addWidget(self.pushButton_DeleteFOTF_2, 0, 2, 1, 1)
        self.pushBottonRefresh_2 = QtWidgets.QPushButton(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushBottonRefresh_2.setFont(font)
        self.pushBottonRefresh_2.setObjectName("pushBottonRefresh_2")
        self.gridLayout_8.addWidget(self.pushBottonRefresh_2, 3, 0, 1, 1)
        self.pushButton_GetOustaloop_2 = QtWidgets.QPushButton(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.pushButton_GetOustaloop_2.setFont(font)
        self.pushButton_GetOustaloop_2.setObjectName("pushButton_GetOustaloop_2")
        self.gridLayout_8.addWidget(self.pushButton_GetOustaloop_2, 3, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_10)
        self.groupBox_8 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_Freq_2 = QtWidgets.QGroupBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.groupBox_Freq_2.setFont(font)
        self.groupBox_Freq_2.setObjectName("groupBox_Freq_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_Freq_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_23 = QtWidgets.QLabel(self.groupBox_Freq_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_Freq_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 0, 0, 1, 1)
        self.bottonBodePlot_2 = QtWidgets.QPushButton(self.groupBox_Freq_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.bottonBodePlot_2.setFont(font)
        self.bottonBodePlot_2.setObjectName("bottonBodePlot_2")
        self.gridLayout_6.addWidget(self.bottonBodePlot_2, 2, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_Freq_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 0, 2, 1, 1)
        self.lineEdit_HigherFreq_2 = QtWidgets.QLineEdit(self.groupBox_Freq_2)
        self.lineEdit_HigherFreq_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_HigherFreq_2.setFont(font)
        self.lineEdit_HigherFreq_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_HigherFreq_2.setObjectName("lineEdit_HigherFreq_2")
        self.gridLayout_6.addWidget(self.lineEdit_HigherFreq_2, 1, 1, 1, 1)
        self.pushButton_StabilityTest_2 = QtWidgets.QPushButton(self.groupBox_Freq_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_StabilityTest_2.setFont(font)
        self.pushButton_StabilityTest_2.setObjectName("pushButton_StabilityTest_2")
        self.gridLayout_6.addWidget(self.pushButton_StabilityTest_2, 2, 1, 1, 1)
        self.pushButtonViewInConsole_2 = QtWidgets.QPushButton(self.groupBox_Freq_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonViewInConsole_2.setFont(font)
        self.pushButtonViewInConsole_2.setObjectName("pushButtonViewInConsole_2")
        self.gridLayout_6.addWidget(self.pushButtonViewInConsole_2, 2, 0, 1, 1)
        self.lineEdit_FreqDataPoints_2 = QtWidgets.QLineEdit(self.groupBox_Freq_2)
        self.lineEdit_FreqDataPoints_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_FreqDataPoints_2.setFont(font)
        self.lineEdit_FreqDataPoints_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_FreqDataPoints_2.setObjectName("lineEdit_FreqDataPoints_2")
        self.gridLayout_6.addWidget(self.lineEdit_FreqDataPoints_2, 1, 2, 1, 1)
        self.lineEdit_LowerFreq_2 = QtWidgets.QLineEdit(self.groupBox_Freq_2)
        self.lineEdit_LowerFreq_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_LowerFreq_2.setFont(font)
        self.lineEdit_LowerFreq_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_LowerFreq_2.setObjectName("lineEdit_LowerFreq_2")
        self.gridLayout_6.addWidget(self.lineEdit_LowerFreq_2, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_Freq_2)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_26 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_7.addWidget(self.label_26, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_7.addWidget(self.label_27, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_9)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_7.addWidget(self.label_28, 0, 2, 1, 1)
        self.lineEdit_StartTime_2 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_StartTime_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_StartTime_2.setFont(font)
        self.lineEdit_StartTime_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_StartTime_2.setObjectName("lineEdit_StartTime_2")
        self.gridLayout_7.addWidget(self.lineEdit_StartTime_2, 1, 0, 1, 1)
        self.lineEdit_StepTime_2 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_StepTime_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_StepTime_2.setFont(font)
        self.lineEdit_StepTime_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_StepTime_2.setObjectName("lineEdit_StepTime_2")
        self.gridLayout_7.addWidget(self.lineEdit_StepTime_2, 1, 1, 1, 1)
        self.lineEdit_StopTime_2 = QtWidgets.QLineEdit(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_StopTime_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_StopTime_2.setSizePolicy(sizePolicy)
        self.lineEdit_StopTime_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_StopTime_2.setFont(font)
        self.lineEdit_StopTime_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_StopTime_2.setObjectName("lineEdit_StopTime_2")
        self.gridLayout_7.addWidget(self.lineEdit_StopTime_2, 1, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_7.addWidget(self.label_29, 2, 0, 1, 1)
        self.label_TimeVector_2 = QtWidgets.QLabel(self.groupBox_9)
        self.label_TimeVector_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_TimeVector_2.setFont(font)
        self.label_TimeVector_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_TimeVector_2.setObjectName("label_TimeVector_2")
        self.gridLayout_7.addWidget(self.label_TimeVector_2, 2, 1, 1, 1)
        self.comboBoxtimeType_2 = QtWidgets.QComboBox(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxtimeType_2.sizePolicy().hasHeightForWidth())
        self.comboBoxtimeType_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxtimeType_2.setFont(font)
        self.comboBoxtimeType_2.setEditable(False)
        self.comboBoxtimeType_2.setCurrentText("")
        self.comboBoxtimeType_2.setMaxVisibleItems(2)
        self.comboBoxtimeType_2.setModelColumn(0)
        self.comboBoxtimeType_2.setObjectName("comboBoxtimeType_2")
        self.gridLayout_7.addWidget(self.comboBoxtimeType_2, 2, 2, 1, 1)
        self.lineEdit_inputTime_2 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_inputTime_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_inputTime_2.setFont(font)
        self.lineEdit_inputTime_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_inputTime_2.setObjectName("lineEdit_inputTime_2")
        self.gridLayout_7.addWidget(self.lineEdit_inputTime_2, 3, 0, 1, 1)
        self.lineEdit_TimeVextorDisplay_2 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_TimeVextorDisplay_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_TimeVextorDisplay_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_TimeVextorDisplay_2.setReadOnly(True)
        self.lineEdit_TimeVextorDisplay_2.setObjectName("lineEdit_TimeVextorDisplay_2")
        self.gridLayout_7.addWidget(self.lineEdit_TimeVextorDisplay_2, 3, 1, 1, 1)
        self.buttoSimulate_2 = QtWidgets.QPushButton(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttoSimulate_2.sizePolicy().hasHeightForWidth())
        self.buttoSimulate_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.buttoSimulate_2.setFont(font)
        self.buttoSimulate_2.setObjectName("buttoSimulate_2")
        self.gridLayout_7.addWidget(self.buttoSimulate_2, 3, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_9)
        self.verticalLayout.addWidget(self.groupBox_8)
        self.label_23.setBuddy(Dialog.lineEdit_HigehrFreq)
        self.label_24.setBuddy(Dialog.lineEdit_LowerFreq)
        self.label_25.setBuddy(Dialog.lineEdit_FreqDataPoints)
        self.label_26.setBuddy(Dialog.lineEdit_StartTime)
        self.label_27.setBuddy(Dialog.lineEdit_StepTime)
        self.label_28.setBuddy(Dialog.lineEdit_StopTime)
        self.label_29.setBuddy(Dialog.lineEdit_inputTime)

        self.retranslateUi(Dialog)
        self.comboBoxtimeType_2.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_10.setTitle(_translate("Dialog", "FO Transfer Functions"))
        self.pushButton_EditFOTF_2.setText(_translate("Dialog", "Edit"))
        self.pushButton_AddFotf_2.setText(_translate("Dialog", "Add"))
        self.pushButton_DeleteFOTF_2.setText(_translate("Dialog", "Delete"))
        self.pushBottonRefresh_2.setText(_translate("Dialog", "Refresh List"))
        self.pushButton_GetOustaloop_2.setText(_translate("Dialog", "Get Oustaloop Model"))
        self.groupBox_8.setTitle(_translate("Dialog", "System Analysis"))
        self.groupBox_Freq_2.setTitle(_translate("Dialog", "Frequency Domain"))
        self.label_23.setText(_translate("Dialog", "Higher Freq (rad/s):"))
        self.label_24.setText(_translate("Dialog", "Lower freq (rad/s):"))
        self.bottonBodePlot_2.setText(_translate("Dialog", "Bode Plot"))
        self.label_25.setText(_translate("Dialog", "Data points (int):"))
        self.lineEdit_HigherFreq_2.setText(_translate("Dialog", "1000"))
        self.pushButton_StabilityTest_2.setText(_translate("Dialog", "Stability test"))
        self.pushButtonViewInConsole_2.setText(_translate("Dialog", "View in console"))
        self.lineEdit_FreqDataPoints_2.setText(_translate("Dialog", "5000"))
        self.lineEdit_LowerFreq_2.setText(_translate("Dialog", "0.001"))
        self.groupBox_9.setTitle(_translate("Dialog", "Time Domain"))
        self.label_26.setText(_translate("Dialog", "Start (s):"))
        self.label_27.setText(_translate("Dialog", "Step (s):"))
        self.label_28.setText(_translate("Dialog", "Stop (s):"))
        self.lineEdit_StartTime_2.setText(_translate("Dialog", "0"))
        self.lineEdit_StepTime_2.setText(_translate("Dialog", "0.1"))
        self.lineEdit_StopTime_2.setText(_translate("Dialog", "30"))
        self.label_29.setText(_translate("Dialog", "Input:"))
        self.label_TimeVector_2.setText(_translate("Dialog", "TimeVector:"))
        self.lineEdit_inputTime_2.setText(_translate("Dialog", "1"))
        self.buttoSimulate_2.setText(_translate("Dialog", "Simulate"))

