# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Set\Documents\CompSys\4th Semeter THESIS\Code\fomcon\guipyQtui\fofopdtpidopt.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FOPIDOPT(object):
    def setupUi(self, FOPIDOPT):
        FOPIDOPT.setObjectName("FOPIDOPT")
        FOPIDOPT.resize(300, 690)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FOPIDOPT.sizePolicy().hasHeightForWidth())
        FOPIDOPT.setSizePolicy(sizePolicy)
        FOPIDOPT.setMinimumSize(QtCore.QSize(300, 690))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(FOPIDOPT)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(FOPIDOPT)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox1 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox1.setMinimumSize(QtCore.QSize(271, 110))
        self.groupBox1.setObjectName("groupBox1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox1)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_18 = QtWidgets.QLabel(self.groupBox1)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 0, 0, 1, 2)
        self.label_19 = QtWidgets.QLabel(self.groupBox1)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 0, 2, 1, 3)
        self.lineEdit_StopFreq = QtWidgets.QLineEdit(self.groupBox1)
        self.lineEdit_StopFreq.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_StopFreq.sizePolicy().hasHeightForWidth())
        self.lineEdit_StopFreq.setSizePolicy(sizePolicy)
        self.lineEdit_StopFreq.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_StopFreq.setFont(font)
        self.lineEdit_StopFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_StopFreq.setObjectName("lineEdit_StopFreq")
        self.gridLayout_3.addWidget(self.lineEdit_StopFreq, 2, 2, 1, 1)
        self.lineEdit_StartFreq = QtWidgets.QLineEdit(self.groupBox1)
        self.lineEdit_StartFreq.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_StartFreq.sizePolicy().hasHeightForWidth())
        self.lineEdit_StartFreq.setSizePolicy(sizePolicy)
        self.lineEdit_StartFreq.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_StartFreq.setFont(font)
        self.lineEdit_StartFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_StartFreq.setObjectName("lineEdit_StartFreq")
        self.gridLayout_3.addWidget(self.lineEdit_StartFreq, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(45, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 3, 1, 1)
        self.lineEditOrder = QtWidgets.QLineEdit(self.groupBox1)
        self.lineEditOrder.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditOrder.sizePolicy().hasHeightForWidth())
        self.lineEditOrder.setSizePolicy(sizePolicy)
        self.lineEditOrder.setMinimumSize(QtCore.QSize(45, 20))
        self.lineEditOrder.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEditOrder.setFont(font)
        self.lineEditOrder.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditOrder.setObjectName("lineEditOrder")
        self.gridLayout_3.addWidget(self.lineEditOrder, 2, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(68, 20))
        self.label_11.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 1)
        self.comboBoxApproxFilter = QtWidgets.QComboBox(self.groupBox1)
        self.comboBoxApproxFilter.setObjectName("comboBoxApproxFilter")
        self.gridLayout_3.addWidget(self.comboBoxApproxFilter, 1, 3, 1, 2)
        self.comboBoxLTISYS = QtWidgets.QComboBox(self.groupBox1)
        self.comboBoxLTISYS.setObjectName("comboBoxLTISYS")
        self.gridLayout_3.addWidget(self.comboBoxLTISYS, 1, 0, 1, 3)
        self.pushButtonAddData = QtWidgets.QPushButton(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAddData.sizePolicy().hasHeightForWidth())
        self.pushButtonAddData.setSizePolicy(sizePolicy)
        self.pushButtonAddData.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButtonAddData.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButtonAddData.setFont(font)
        self.pushButtonAddData.setObjectName("pushButtonAddData")
        self.gridLayout_3.addWidget(self.pushButtonAddData, 3, 0, 1, 1)
        self.pushButtonDeleteData = QtWidgets.QPushButton(self.groupBox1)
        self.pushButtonDeleteData.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDeleteData.sizePolicy().hasHeightForWidth())
        self.pushButtonDeleteData.setSizePolicy(sizePolicy)
        self.pushButtonDeleteData.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButtonDeleteData.setObjectName("pushButtonDeleteData")
        self.gridLayout_3.addWidget(self.pushButtonDeleteData, 3, 1, 1, 2)
        self.pushButtonAddData_2 = QtWidgets.QPushButton(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAddData_2.sizePolicy().hasHeightForWidth())
        self.pushButtonAddData_2.setSizePolicy(sizePolicy)
        self.pushButtonAddData_2.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButtonAddData_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButtonAddData_2.setFont(font)
        self.pushButtonAddData_2.setObjectName("pushButtonAddData_2")
        self.gridLayout_3.addWidget(self.pushButtonAddData_2, 3, 3, 1, 2)
        self.verticalLayout_3.addWidget(self.groupBox1)
        self.groupBox2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox2.setMinimumSize(QtCore.QSize(259, 204))
        self.groupBox2.setCheckable(True)
        self.groupBox2.setObjectName("groupBox2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox2)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBoxTuneOption = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBoxTuneOption.setObjectName("comboBoxTuneOption")
        self.gridLayout.addWidget(self.comboBoxTuneOption, 0, 0, 2, 2)
        spacerItem = QtWidgets.QSpacerItem(13, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 7, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_8.setLineWidth(2)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 3, 1, 2)
        self.lineEdit_Kp = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Kp.sizePolicy().hasHeightForWidth())
        self.lineEdit_Kp.setSizePolicy(sizePolicy)
        self.lineEdit_Kp.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_Kp.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Kp.setObjectName("lineEdit_Kp")
        self.gridLayout.addWidget(self.lineEdit_Kp, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 4, 1, 1)
        self.lineEditConstMaxMu = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditConstMaxMu.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditConstMaxMu.setObjectName("lineEditConstMaxMu")
        self.gridLayout.addWidget(self.lineEditConstMaxMu, 6, 4, 1, 1)
        self.lineEditConstMaxKp = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditConstMaxKp.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditConstMaxKp.setObjectName("lineEditConstMaxKp")
        self.gridLayout.addWidget(self.lineEditConstMaxKp, 2, 4, 1, 1)
        self.lineEdit_Kd = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Kd.sizePolicy().hasHeightForWidth())
        self.lineEdit_Kd.setSizePolicy(sizePolicy)
        self.lineEdit_Kd.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Kd.setObjectName("lineEdit_Kd")
        self.gridLayout.addWidget(self.lineEdit_Kd, 5, 1, 1, 1)
        self.lineEditConstMinKi = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditConstMinKi.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditConstMinKi.setObjectName("lineEditConstMinKi")
        self.gridLayout.addWidget(self.lineEditConstMinKi, 3, 3, 1, 1)
        self.lineEdit_Lam = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Lam.sizePolicy().hasHeightForWidth())
        self.lineEdit_Lam.setSizePolicy(sizePolicy)
        self.lineEdit_Lam.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Lam.setObjectName("lineEdit_Lam")
        self.gridLayout.addWidget(self.lineEdit_Lam, 4, 1, 1, 1)
        self.lineEditConstMinlam = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditConstMinlam.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditConstMinlam.setObjectName("lineEditConstMinlam")
        self.gridLayout.addWidget(self.lineEditConstMinlam, 4, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(20, 13))
        self.label_6.setMaximumSize(QtCore.QSize(20, 13))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(20, 13))
        self.label_5.setMaximumSize(QtCore.QSize(20, 13))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.lineEditConstMinMu = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditConstMinMu.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditConstMinMu.setObjectName("lineEditConstMinMu")
        self.gridLayout.addWidget(self.lineEditConstMinMu, 6, 3, 1, 1)
        self.lineEditConstMaxKi = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditConstMaxKi.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditConstMaxKi.setObjectName("lineEditConstMaxKi")
        self.gridLayout.addWidget(self.lineEditConstMaxKi, 3, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(20, 13))
        self.label_7.setMaximumSize(QtCore.QSize(20, 13))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(13, 13))
        self.label_3.setMaximumSize(QtCore.QSize(20, 13))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEditConstMinKp = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditConstMinKp.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditConstMinKp.setObjectName("lineEditConstMinKp")
        self.gridLayout.addWidget(self.lineEditConstMinKp, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(20, 13))
        self.label_4.setMaximumSize(QtCore.QSize(20, 13))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_Ki = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Ki.sizePolicy().hasHeightForWidth())
        self.lineEdit_Ki.setSizePolicy(sizePolicy)
        self.lineEdit_Ki.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Ki.setObjectName("lineEdit_Ki")
        self.gridLayout.addWidget(self.lineEdit_Ki, 3, 1, 1, 1)
        self.lineEditConstMaxlam = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditConstMaxlam.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditConstMaxlam.setObjectName("lineEditConstMaxlam")
        self.gridLayout.addWidget(self.lineEditConstMaxlam, 4, 4, 1, 1)
        self.lineEditConstMaxKd = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditConstMaxKd.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditConstMaxKd.setObjectName("lineEditConstMaxKd")
        self.gridLayout.addWidget(self.lineEditConstMaxKd, 5, 4, 1, 1)
        self.lineEditConstMinKd = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditConstMinKd.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditConstMinKd.setObjectName("lineEditConstMinKd")
        self.gridLayout.addWidget(self.lineEditConstMinKd, 5, 3, 1, 1)
        self.lineEdit_Mu = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Mu.sizePolicy().hasHeightForWidth())
        self.lineEdit_Mu.setSizePolicy(sizePolicy)
        self.lineEdit_Mu.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Mu.setObjectName("lineEdit_Mu")
        self.gridLayout.addWidget(self.lineEdit_Mu, 6, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(2, -1, 2, -1)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonSetParams = QtWidgets.QPushButton(self.groupBox2)
        self.pushButtonSetParams.setObjectName("pushButtonSetParams")
        self.horizontalLayout.addWidget(self.pushButtonSetParams)
        self.comboBoxParamSetOption = QtWidgets.QComboBox(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxParamSetOption.sizePolicy().hasHeightForWidth())
        self.comboBoxParamSetOption.setSizePolicy(sizePolicy)
        self.comboBoxParamSetOption.setObjectName("comboBoxParamSetOption")
        self.horizontalLayout.addWidget(self.comboBoxParamSetOption)
        self.label_9 = QtWidgets.QLabel(self.groupBox2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.lineEdit_ParamsResetValue = QtWidgets.QLineEdit(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ParamsResetValue.sizePolicy().hasHeightForWidth())
        self.lineEdit_ParamsResetValue.setSizePolicy(sizePolicy)
        self.lineEdit_ParamsResetValue.setMaximumSize(QtCore.QSize(40, 20))
        self.lineEdit_ParamsResetValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ParamsResetValue.setObjectName("lineEdit_ParamsResetValue")
        self.horizontalLayout.addWidget(self.lineEdit_ParamsResetValue)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.groupBox2)
        self.groupBox3 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox3.sizePolicy().hasHeightForWidth())
        self.groupBox3.setSizePolicy(sizePolicy)
        self.groupBox3.setMinimumSize(QtCore.QSize(221, 71))
        self.groupBox3.setObjectName("groupBox3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_12 = QtWidgets.QLabel(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_SimMaxTime = QtWidgets.QLineEdit(self.groupBox3)
        self.lineEdit_SimMaxTime.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_SimMaxTime.sizePolicy().hasHeightForWidth())
        self.lineEdit_SimMaxTime.setSizePolicy(sizePolicy)
        self.lineEdit_SimMaxTime.setMinimumSize(QtCore.QSize(40, 20))
        self.lineEdit_SimMaxTime.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_SimMaxTime.setFont(font)
        self.lineEdit_SimMaxTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_SimMaxTime.setObjectName("lineEdit_SimMaxTime")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_SimMaxTime)
        self.label_13 = QtWidgets.QLabel(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lineEdit_StepMin = QtWidgets.QLineEdit(self.groupBox3)
        self.lineEdit_StepMin.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_StepMin.sizePolicy().hasHeightForWidth())
        self.lineEdit_StepMin.setSizePolicy(sizePolicy)
        self.lineEdit_StepMin.setMinimumSize(QtCore.QSize(40, 20))
        self.lineEdit_StepMin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_StepMin.setFont(font)
        self.lineEdit_StepMin.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_StepMin.setObjectName("lineEdit_StepMin")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_StepMin)
        self.verticalLayout_3.addWidget(self.groupBox3)
        self.groupBox4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox4.setMinimumSize(QtCore.QSize(241, 61))
        self.groupBox4.setCheckable(True)
        self.groupBox4.setObjectName("groupBox4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox4)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.formLayout_2.setContentsMargins(5, 5, 5, 5)
        self.formLayout_2.setSpacing(5)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(50, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lineEdit_3)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.checkBox_3)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.groupBox5 = QtWidgets.QGroupBox(self.groupBox4)
        self.groupBox5.setObjectName("groupBox5")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox5)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setSpacing(5)
        self.formLayout.setObjectName("formLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox5)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(50, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lineEdit_2)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox5)
        self.checkBox_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.checkBox_2)
        self.horizontalLayout_2.addWidget(self.groupBox5)
        self.verticalLayout_3.addWidget(self.groupBox4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setMinimumSize(QtCore.QSize(261, 81))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAcceptDrops(False)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(True)
        self.groupBox_3.setChecked(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setMinimumSize(QtCore.QSize(90, 0))
        self.label_15.setMaximumSize(QtCore.QSize(124, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setMinimumSize(QtCore.QSize(40, 0))
        self.label_17.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setLineWidth(1)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(112, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 0, 1, 1)
        self.lineEdit_Kp_2 = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Kp_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_Kp_2.setSizePolicy(sizePolicy)
        self.lineEdit_Kp_2.setMinimumSize(QtCore.QSize(90, 20))
        self.lineEdit_Kp_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_Kp_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Kp_2.setObjectName("lineEdit_Kp_2")
        self.gridLayout_4.addWidget(self.lineEdit_Kp_2, 1, 1, 1, 1)
        self.lineEdit_Kp_3 = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Kp_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_Kp_3.setSizePolicy(sizePolicy)
        self.lineEdit_Kp_3.setMinimumSize(QtCore.QSize(90, 20))
        self.lineEdit_Kp_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_Kp_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Kp_3.setObjectName("lineEdit_Kp_3")
        self.gridLayout_4.addWidget(self.lineEdit_Kp_3, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(112, 20))
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 2, 0, 1, 1)
        self.lineEdit_Kp_5 = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Kp_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_Kp_5.setSizePolicy(sizePolicy)
        self.lineEdit_Kp_5.setMinimumSize(QtCore.QSize(35, 20))
        self.lineEdit_Kp_5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_Kp_5.setMaxLength(5)
        self.lineEdit_Kp_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Kp_5.setObjectName("lineEdit_Kp_5")
        self.gridLayout_4.addWidget(self.lineEdit_Kp_5, 1, 2, 1, 1)
        self.lineEdit_Kp_4 = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Kp_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_Kp_4.setSizePolicy(sizePolicy)
        self.lineEdit_Kp_4.setMinimumSize(QtCore.QSize(35, 20))
        self.lineEdit_Kp_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_Kp_4.setMaxLength(5)
        self.lineEdit_Kp_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Kp_4.setObjectName("lineEdit_Kp_4")
        self.gridLayout_4.addWidget(self.lineEdit_Kp_4, 2, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonDeleteData_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonDeleteData_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDeleteData_2.sizePolicy().hasHeightForWidth())
        self.pushButtonDeleteData_2.setSizePolicy(sizePolicy)
        self.pushButtonDeleteData_2.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButtonDeleteData_2.setObjectName("pushButtonDeleteData_2")
        self.horizontalLayout_3.addWidget(self.pushButtonDeleteData_2)
        self.pushButtonPlotData = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonPlotData.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPlotData.sizePolicy().hasHeightForWidth())
        self.pushButtonPlotData.setSizePolicy(sizePolicy)
        self.pushButtonPlotData.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButtonPlotData.setObjectName("pushButtonPlotData")
        self.horizontalLayout_3.addWidget(self.pushButtonPlotData)
        self.pushButtonTrimData = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonTrimData.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonTrimData.sizePolicy().hasHeightForWidth())
        self.pushButtonTrimData.setSizePolicy(sizePolicy)
        self.pushButtonTrimData.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButtonTrimData.setObjectName("pushButtonTrimData")
        self.horizontalLayout_3.addWidget(self.pushButtonTrimData)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 3, 0, 1, 3)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.horizontalLayout_4.addWidget(self.groupBox)

        self.retranslateUi(FOPIDOPT)
        QtCore.QMetaObject.connectSlotsByName(FOPIDOPT)

    def retranslateUi(self, FOPIDOPT):
        _translate = QtCore.QCoreApplication.translate
        FOPIDOPT.setWindowTitle(_translate("FOPIDOPT", "Form"))
        self.groupBox.setTitle(_translate("FOPIDOPT", "FO - FOPDT Plant Controller and Tunner"))
        self.groupBox1.setTitle(_translate("FOPIDOPT", "Plant Model"))
        self.label_18.setText(_translate("FOPIDOPT", "FO - FOPDT"))
        self.label_19.setText(_translate("FOPIDOPT", "Approximate as"))
        self.lineEdit_StopFreq.setText(_translate("FOPIDOPT", "4"))
        self.lineEdit_StopFreq.setPlaceholderText(_translate("FOPIDOPT", "Stop (int)"))
        self.lineEdit_StartFreq.setText(_translate("FOPIDOPT", "-4"))
        self.lineEdit_StartFreq.setPlaceholderText(_translate("FOPIDOPT", "Start (int)"))
        self.label_10.setText(_translate("FOPIDOPT", "of Order:"))
        self.lineEditOrder.setText(_translate("FOPIDOPT", "5"))
        self.lineEditOrder.setPlaceholderText(_translate("FOPIDOPT", "(int)"))
        self.label_11.setText(_translate("FOPIDOPT", "<html><head/><body><p>Freq(w):10^</p></body></html>"))
        self.pushButtonAddData.setText(_translate("FOPIDOPT", "Add"))
        self.pushButtonDeleteData.setText(_translate("FOPIDOPT", "Delete"))
        self.pushButtonAddData_2.setText(_translate("FOPIDOPT", "Tune FOPID"))
        self.groupBox2.setTitle(_translate("FOPIDOPT", "Fractional PID Controller Parameters"))
        self.label_8.setText(_translate("FOPIDOPT", "Constraints"))
        self.lineEdit_Kp.setText(_translate("FOPIDOPT", "1"))
        self.label.setText(_translate("FOPIDOPT", "Min"))
        self.label_2.setText(_translate("FOPIDOPT", "Max"))
        self.lineEditConstMaxMu.setText(_translate("FOPIDOPT", "0.9"))
        self.lineEditConstMaxKp.setText(_translate("FOPIDOPT", "2.0"))
        self.lineEdit_Kd.setText(_translate("FOPIDOPT", "1"))
        self.lineEditConstMinKi.setText(_translate("FOPIDOPT", "0"))
        self.lineEdit_Lam.setText(_translate("FOPIDOPT", "0.9"))
        self.lineEditConstMinlam.setText(_translate("FOPIDOPT", "0.01"))
        self.label_6.setText(_translate("FOPIDOPT", "Kd:"))
        self.label_5.setText(_translate("FOPIDOPT", "lam:"))
        self.lineEditConstMinMu.setText(_translate("FOPIDOPT", "0.01"))
        self.lineEditConstMaxKi.setText(_translate("FOPIDOPT", "2.0"))
        self.label_7.setText(_translate("FOPIDOPT", "mu:"))
        self.label_3.setText(_translate("FOPIDOPT", "Kp:"))
        self.lineEditConstMinKp.setText(_translate("FOPIDOPT", "0"))
        self.label_4.setText(_translate("FOPIDOPT", "Ki:"))
        self.lineEdit_Ki.setText(_translate("FOPIDOPT", "1"))
        self.lineEditConstMaxlam.setText(_translate("FOPIDOPT", "0.9"))
        self.lineEditConstMaxKd.setText(_translate("FOPIDOPT", "2.5"))
        self.lineEditConstMinKd.setText(_translate("FOPIDOPT", "0"))
        self.lineEdit_Mu.setText(_translate("FOPIDOPT", "0.5"))
        self.pushButtonSetParams.setText(_translate("FOPIDOPT", "Set"))
        self.label_9.setText(_translate("FOPIDOPT", "to"))
        self.lineEdit_ParamsResetValue.setText(_translate("FOPIDOPT", "1"))
        self.groupBox3.setTitle(_translate("FOPIDOPT", "Simulation Parameters"))
        self.label_12.setText(_translate("FOPIDOPT", "No. of Iteration: "))
        self.lineEdit_SimMaxTime.setText(_translate("FOPIDOPT", "10"))
        self.lineEdit_SimMaxTime.setPlaceholderText(_translate("FOPIDOPT", "Start (int)"))
        self.label_13.setText(_translate("FOPIDOPT", "Sampling Rate (Hz) = 1/step :"))
        self.lineEdit_StepMin.setText(_translate("FOPIDOPT", "0.01"))
        self.lineEdit_StepMin.setPlaceholderText(_translate("FOPIDOPT", "Start (int)"))
        self.groupBox4.setTitle(_translate("FOPIDOPT", "Gain and Phase Margin"))
        self.groupBox_2.setTitle(_translate("FOPIDOPT", "Gain margin[dB]"))
        self.lineEdit_3.setText(_translate("FOPIDOPT", "15"))
        self.checkBox_3.setText(_translate("FOPIDOPT", "Exact"))
        self.groupBox5.setTitle(_translate("FOPIDOPT", "Phase margin[deg]"))
        self.lineEdit_2.setText(_translate("FOPIDOPT", "60"))
        self.checkBox_2.setText(_translate("FOPIDOPT", "Exact"))
        self.groupBox_3.setTitle(_translate("FOPIDOPT", "Tank Control"))
        self.label_15.setText(_translate("FOPIDOPT", "IP Address"))
        self.label_17.setText(_translate("FOPIDOPT", "Port"))
        self.label_14.setText(_translate("FOPIDOPT", "FomconPy\'s Receiving: "))
        self.lineEdit_Kp_2.setText(_translate("FOPIDOPT", "127.0.0.1"))
        self.lineEdit_Kp_3.setText(_translate("FOPIDOPT", "127.0.0.1"))
        self.label_16.setText(_translate("FOPIDOPT", "FomconPy\'s Sending: "))
        self.lineEdit_Kp_5.setText(_translate("FOPIDOPT", "25000"))
        self.lineEdit_Kp_4.setText(_translate("FOPIDOPT", "25001"))
        self.pushButtonDeleteData_2.setText(_translate("FOPIDOPT", "Test Connection"))
        self.pushButtonPlotData.setText(_translate("FOPIDOPT", "Start"))
        self.pushButtonTrimData.setText(_translate("FOPIDOPT", "Stop"))

