# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Set\Documents\CompSys\4th Semeter THESIS\Code\fomcon\guipyQtui\fopidoptgui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FOPIDOPT(object):
    def setupUi(self, FOPIDOPT):
        FOPIDOPT.setObjectName("FOPIDOPT")
        FOPIDOPT.resize(440, 785)
        FOPIDOPT.setMinimumSize(QtCore.QSize(440, 785))
        self.centralwidget = QtWidgets.QWidget(FOPIDOPT)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(330, 140))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBoxFOFOPDTSYS = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxFOFOPDTSYS.sizePolicy().hasHeightForWidth())
        self.comboBoxFOFOPDTSYS.setSizePolicy(sizePolicy)
        self.comboBoxFOFOPDTSYS.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBoxFOFOPDTSYS.setInsertPolicy(QtWidgets.QComboBox.InsertAfterCurrent)
        self.comboBoxFOFOPDTSYS.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBoxFOFOPDTSYS.setObjectName("comboBoxFOFOPDTSYS")
        self.gridLayout_3.addWidget(self.comboBoxFOFOPDTSYS, 1, 0, 1, 2)
        self.comboBoxApproxFilter = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxApproxFilter.sizePolicy().hasHeightForWidth())
        self.comboBoxApproxFilter.setSizePolicy(sizePolicy)
        self.comboBoxApproxFilter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBoxApproxFilter.setInsertPolicy(QtWidgets.QComboBox.InsertAfterCurrent)
        self.comboBoxApproxFilter.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBoxApproxFilter.setObjectName("comboBoxApproxFilter")
        self.gridLayout_3.addWidget(self.comboBoxApproxFilter, 1, 2, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(68, 20))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(68, 20))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 2, 1, 1, 1)
        self.lineEdit_StartFreq = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_StartFreq.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_StartFreq.sizePolicy().hasHeightForWidth())
        self.lineEdit_StartFreq.setSizePolicy(sizePolicy)
        self.lineEdit_StartFreq.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_StartFreq.setFont(font)
        self.lineEdit_StartFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_StartFreq.setObjectName("lineEdit_StartFreq")
        self.gridLayout_3.addWidget(self.lineEdit_StartFreq, 3, 0, 1, 1)
        self.lineEdit_StopFreq = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_StopFreq.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_StopFreq.sizePolicy().hasHeightForWidth())
        self.lineEdit_StopFreq.setSizePolicy(sizePolicy)
        self.lineEdit_StopFreq.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_StopFreq.setFont(font)
        self.lineEdit_StopFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_StopFreq.setObjectName("lineEdit_StopFreq")
        self.gridLayout_3.addWidget(self.lineEdit_StopFreq, 3, 1, 1, 1)
        self.pushButtonAddData = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAddData.sizePolicy().hasHeightForWidth())
        self.pushButtonAddData.setSizePolicy(sizePolicy)
        self.pushButtonAddData.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonAddData.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAddData.setFont(font)
        self.pushButtonAddData.setObjectName("pushButtonAddData")
        self.gridLayout_3.addWidget(self.pushButtonAddData, 4, 0, 1, 1)
        self.pushButtonEditData = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonEditData.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonEditData.sizePolicy().hasHeightForWidth())
        self.pushButtonEditData.setSizePolicy(sizePolicy)
        self.pushButtonEditData.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonEditData.setFont(font)
        self.pushButtonEditData.setObjectName("pushButtonEditData")
        self.gridLayout_3.addWidget(self.pushButtonEditData, 4, 1, 1, 1)
        self.pushButtonDeleteData = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonDeleteData.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDeleteData.sizePolicy().hasHeightForWidth())
        self.pushButtonDeleteData.setSizePolicy(sizePolicy)
        self.pushButtonDeleteData.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonDeleteData.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDeleteData.setFont(font)
        self.pushButtonDeleteData.setObjectName("pushButtonDeleteData")
        self.gridLayout_3.addWidget(self.pushButtonDeleteData, 4, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 0, 2, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 0, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 0))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 2, 1, 1)
        self.lineEditOrder = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditOrder.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditOrder.sizePolicy().hasHeightForWidth())
        self.lineEditOrder.setSizePolicy(sizePolicy)
        self.lineEditOrder.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEditOrder.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEditOrder.setFont(font)
        self.lineEditOrder.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditOrder.setObjectName("lineEditOrder")
        self.gridLayout_3.addWidget(self.lineEditOrder, 3, 2, 1, 1)
        self.pushButtonTune = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonTune.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonTune.sizePolicy().hasHeightForWidth())
        self.pushButtonTune.setSizePolicy(sizePolicy)
        self.pushButtonTune.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonTune.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonTune.setFont(font)
        self.pushButtonTune.setObjectName("pushButtonTune")
        self.gridLayout_3.addWidget(self.pushButtonTune, 3, 3, 2, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBoxFOPIDParams = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxFOPIDParams.setMinimumSize(QtCore.QSize(259, 204))
        self.groupBoxFOPIDParams.setCheckable(True)
        self.groupBoxFOPIDParams.setChecked(True)
        self.groupBoxFOPIDParams.setObjectName("groupBoxFOPIDParams")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxFOPIDParams)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBoxFOPIDParams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(13, 13))
        self.label_3.setMaximumSize(QtCore.QSize(20, 13))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_Ki = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Ki.sizePolicy().hasHeightForWidth())
        self.lineEdit_Ki.setSizePolicy(sizePolicy)
        self.lineEdit_Ki.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Ki.setObjectName("lineEdit_Ki")
        self.gridLayout.addWidget(self.lineEdit_Ki, 3, 1, 1, 1)
        self.lineEditConstMinMu = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditConstMinMu.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditConstMinMu.sizePolicy().hasHeightForWidth())
        self.lineEditConstMinMu.setSizePolicy(sizePolicy)
        self.lineEditConstMinMu.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditConstMinMu.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditConstMinMu.setObjectName("lineEditConstMinMu")
        self.gridLayout.addWidget(self.lineEditConstMinMu, 6, 3, 1, 1)
        self.lineEditConstMaxKi = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditConstMaxKi.sizePolicy().hasHeightForWidth())
        self.lineEditConstMaxKi.setSizePolicy(sizePolicy)
        self.lineEditConstMaxKi.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditConstMaxKi.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditConstMaxKi.setObjectName("lineEditConstMaxKi")
        self.gridLayout.addWidget(self.lineEditConstMaxKi, 3, 4, 1, 1)
        self.lineEditConstMinKp = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditConstMinKp.sizePolicy().hasHeightForWidth())
        self.lineEditConstMinKp.setSizePolicy(sizePolicy)
        self.lineEditConstMinKp.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditConstMinKp.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditConstMinKp.setObjectName("lineEditConstMinKp")
        self.gridLayout.addWidget(self.lineEditConstMinKp, 2, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(20, 13))
        self.label_5.setMaximumSize(QtCore.QSize(20, 13))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(20, 13))
        self.label_6.setMaximumSize(QtCore.QSize(20, 13))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.lineEditConstMaxKd = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditConstMaxKd.sizePolicy().hasHeightForWidth())
        self.lineEditConstMaxKd.setSizePolicy(sizePolicy)
        self.lineEditConstMaxKd.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditConstMaxKd.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditConstMaxKd.setObjectName("lineEditConstMaxKd")
        self.gridLayout.addWidget(self.lineEditConstMaxKd, 5, 4, 1, 1)
        self.lineEdit_Mu = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Mu.sizePolicy().hasHeightForWidth())
        self.lineEdit_Mu.setSizePolicy(sizePolicy)
        self.lineEdit_Mu.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Mu.setObjectName("lineEdit_Mu")
        self.gridLayout.addWidget(self.lineEdit_Mu, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(20, 13))
        self.label_7.setMaximumSize(QtCore.QSize(20, 13))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(20, 13))
        self.label_4.setMaximumSize(QtCore.QSize(20, 13))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEditConstMaxlam = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditConstMaxlam.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditConstMaxlam.sizePolicy().hasHeightForWidth())
        self.lineEditConstMaxlam.setSizePolicy(sizePolicy)
        self.lineEditConstMaxlam.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditConstMaxlam.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditConstMaxlam.setObjectName("lineEditConstMaxlam")
        self.gridLayout.addWidget(self.lineEditConstMaxlam, 4, 4, 1, 1)
        self.lineEditConstMinKd = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditConstMinKd.sizePolicy().hasHeightForWidth())
        self.lineEditConstMinKd.setSizePolicy(sizePolicy)
        self.lineEditConstMinKd.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditConstMinKd.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditConstMinKd.setObjectName("lineEditConstMinKd")
        self.gridLayout.addWidget(self.lineEditConstMinKd, 5, 3, 1, 1)
        self.comboBoxTuneOption = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxTuneOption.sizePolicy().hasHeightForWidth())
        self.comboBoxTuneOption.setSizePolicy(sizePolicy)
        self.comboBoxTuneOption.setObjectName("comboBoxTuneOption")
        self.gridLayout.addWidget(self.comboBoxTuneOption, 1, 1, 1, 1)
        self.lineEdit_Kd = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Kd.sizePolicy().hasHeightForWidth())
        self.lineEdit_Kd.setSizePolicy(sizePolicy)
        self.lineEdit_Kd.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Kd.setObjectName("lineEdit_Kd")
        self.gridLayout.addWidget(self.lineEdit_Kd, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 4, 1, 1)
        self.lineEdit_Kp = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Kp.sizePolicy().hasHeightForWidth())
        self.lineEdit_Kp.setSizePolicy(sizePolicy)
        self.lineEdit_Kp.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_Kp.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Kp.setObjectName("lineEdit_Kp")
        self.gridLayout.addWidget(self.lineEdit_Kp, 2, 1, 1, 1)
        self.lineEditConstMinKi = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditConstMinKi.sizePolicy().hasHeightForWidth())
        self.lineEditConstMinKi.setSizePolicy(sizePolicy)
        self.lineEditConstMinKi.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditConstMinKi.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditConstMinKi.setObjectName("lineEditConstMinKi")
        self.gridLayout.addWidget(self.lineEditConstMinKi, 3, 3, 1, 1)
        self.lineEdit_Lam = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Lam.sizePolicy().hasHeightForWidth())
        self.lineEdit_Lam.setSizePolicy(sizePolicy)
        self.lineEdit_Lam.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Lam.setObjectName("lineEdit_Lam")
        self.gridLayout.addWidget(self.lineEdit_Lam, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 7, 1)
        self.lineEditConstMaxMu = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditConstMaxMu.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditConstMaxMu.sizePolicy().hasHeightForWidth())
        self.lineEditConstMaxMu.setSizePolicy(sizePolicy)
        self.lineEditConstMaxMu.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditConstMaxMu.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditConstMaxMu.setObjectName("lineEditConstMaxMu")
        self.gridLayout.addWidget(self.lineEditConstMaxMu, 6, 4, 1, 1)
        self.lineEditConstMaxKp = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditConstMaxKp.sizePolicy().hasHeightForWidth())
        self.lineEditConstMaxKp.setSizePolicy(sizePolicy)
        self.lineEditConstMaxKp.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditConstMaxKp.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditConstMaxKp.setObjectName("lineEditConstMaxKp")
        self.gridLayout.addWidget(self.lineEditConstMaxKp, 2, 4, 1, 1)
        self.lineEditConstMinlam = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditConstMinlam.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditConstMinlam.sizePolicy().hasHeightForWidth())
        self.lineEditConstMinlam.setSizePolicy(sizePolicy)
        self.lineEditConstMinlam.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditConstMinlam.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditConstMinlam.setObjectName("lineEditConstMinlam")
        self.gridLayout.addWidget(self.lineEditConstMinlam, 4, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_8.setLineWidth(2)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 3, 1, 2)
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(68, 20))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBoxFOPIDParams)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonSetParams = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSetParams.sizePolicy().hasHeightForWidth())
        self.pushButtonSetParams.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSetParams.setFont(font)
        self.pushButtonSetParams.setObjectName("pushButtonSetParams")
        self.gridLayout_2.addWidget(self.pushButtonSetParams, 1, 0, 1, 1)
        self.comboBoxParamSetOption = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxParamSetOption.sizePolicy().hasHeightForWidth())
        self.comboBoxParamSetOption.setSizePolicy(sizePolicy)
        self.comboBoxParamSetOption.setObjectName("comboBoxParamSetOption")
        self.gridLayout_2.addWidget(self.comboBoxParamSetOption, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 2, 1, 1)
        self.lineEditParamsValue = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditParamsValue.sizePolicy().hasHeightForWidth())
        self.lineEditParamsValue.setSizePolicy(sizePolicy)
        self.lineEditParamsValue.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEditParamsValue.setInputMask("")
        self.lineEditParamsValue.setMaxLength(32767)
        self.lineEditParamsValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditParamsValue.setObjectName("lineEditParamsValue")
        self.gridLayout_2.addWidget(self.lineEditParamsValue, 1, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.verticalLayout_2.addWidget(self.groupBoxFOPIDParams)
        self.groupBoxSimParams = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxSimParams.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxSimParams.sizePolicy().hasHeightForWidth())
        self.groupBoxSimParams.setSizePolicy(sizePolicy)
        self.groupBoxSimParams.setMinimumSize(QtCore.QSize(221, 71))
        self.groupBoxSimParams.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBoxSimParams.setCheckable(True)
        self.groupBoxSimParams.setChecked(True)
        self.groupBoxSimParams.setObjectName("groupBoxSimParams")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBoxSimParams)
        self.formLayout_3.setContentsMargins(5, 5, 5, 5)
        self.formLayout_3.setSpacing(5)
        self.formLayout_3.setObjectName("formLayout_3")
        self.labelIter = QtWidgets.QLabel(self.groupBoxSimParams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelIter.sizePolicy().hasHeightForWidth())
        self.labelIter.setSizePolicy(sizePolicy)
        self.labelIter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelIter.setAlignment(QtCore.Qt.AlignCenter)
        self.labelIter.setObjectName("labelIter")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelIter)
        self.lineEditIter = QtWidgets.QLineEdit(self.groupBoxSimParams)
        self.lineEditIter.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditIter.sizePolicy().hasHeightForWidth())
        self.lineEditIter.setSizePolicy(sizePolicy)
        self.lineEditIter.setMinimumSize(QtCore.QSize(40, 20))
        self.lineEditIter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEditIter.setFont(font)
        self.lineEditIter.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditIter.setObjectName("lineEditIter")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditIter)
        self.labelStep = QtWidgets.QLabel(self.groupBoxSimParams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStep.sizePolicy().hasHeightForWidth())
        self.labelStep.setSizePolicy(sizePolicy)
        self.labelStep.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelStep.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStep.setObjectName("labelStep")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelStep)
        self.lineEditDt = QtWidgets.QLineEdit(self.groupBoxSimParams)
        self.lineEditDt.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditDt.sizePolicy().hasHeightForWidth())
        self.lineEditDt.setSizePolicy(sizePolicy)
        self.lineEditDt.setMinimumSize(QtCore.QSize(40, 20))
        self.lineEditDt.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEditDt.setFont(font)
        self.lineEditDt.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditDt.setDragEnabled(False)
        self.lineEditDt.setClearButtonEnabled(False)
        self.lineEditDt.setObjectName("lineEditDt")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditDt)
        self.verticalLayout_2.addWidget(self.groupBoxSimParams)
        self.groupBoxGainPhaseMargin = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxGainPhaseMargin.setEnabled(True)
        self.groupBoxGainPhaseMargin.setMinimumSize(QtCore.QSize(241, 61))
        self.groupBoxGainPhaseMargin.setAutoFillBackground(True)
        self.groupBoxGainPhaseMargin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxGainPhaseMargin.setCheckable(True)
        self.groupBoxGainPhaseMargin.setChecked(True)
        self.groupBoxGainPhaseMargin.setObjectName("groupBoxGainPhaseMargin")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBoxGainPhaseMargin)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBoxGainPhaseMargin)
        self.groupBox_8.setEnabled(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_8)
        self.formLayout_2.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.formLayout_2.setContentsMargins(5, 5, 5, 5)
        self.formLayout_2.setSpacing(5)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lineEditGainMargin = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEditGainMargin.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditGainMargin.sizePolicy().hasHeightForWidth())
        self.lineEditGainMargin.setSizePolicy(sizePolicy)
        self.lineEditGainMargin.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEditGainMargin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEditGainMargin.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditGainMargin.setObjectName("lineEditGainMargin")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lineEditGainMargin)
        self.checkBoxGainMargin = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBoxGainMargin.setMaximumSize(QtCore.QSize(60, 16777215))
        self.checkBoxGainMargin.setChecked(True)
        self.checkBoxGainMargin.setObjectName("checkBoxGainMargin")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.checkBoxGainMargin)
        self.horizontalLayout.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBoxGainPhaseMargin)
        self.groupBox_9.setEnabled(True)
        self.groupBox_9.setObjectName("groupBox_9")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_9)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setSpacing(5)
        self.formLayout.setObjectName("formLayout")
        self.lineEditPhaseMargin = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEditPhaseMargin.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPhaseMargin.sizePolicy().hasHeightForWidth())
        self.lineEditPhaseMargin.setSizePolicy(sizePolicy)
        self.lineEditPhaseMargin.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEditPhaseMargin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEditPhaseMargin.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditPhaseMargin.setObjectName("lineEditPhaseMargin")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lineEditPhaseMargin)
        self.checkBoxPhaseMargin = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBoxPhaseMargin.setMaximumSize(QtCore.QSize(60, 16777215))
        self.checkBoxPhaseMargin.setChecked(True)
        self.checkBoxPhaseMargin.setObjectName("checkBoxPhaseMargin")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.checkBoxPhaseMargin)
        self.horizontalLayout.addWidget(self.groupBox_9)
        self.verticalLayout_2.addWidget(self.groupBoxGainPhaseMargin)
        self.groupBoxTankControl = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxTankControl.setEnabled(True)
        self.groupBoxTankControl.setMinimumSize(QtCore.QSize(431, 125))
        self.groupBoxTankControl.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxTankControl.setFont(font)
        self.groupBoxTankControl.setAcceptDrops(False)
        self.groupBoxTankControl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxTankControl.setFlat(False)
        self.groupBoxTankControl.setCheckable(True)
        self.groupBoxTankControl.setChecked(True)
        self.groupBoxTankControl.setObjectName("groupBoxTankControl")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxTankControl)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_28 = QtWidgets.QLabel(self.groupBoxTankControl)
        self.label_28.setMinimumSize(QtCore.QSize(90, 0))
        self.label_28.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 0, 0, 1, 1)
        self.lineEditRecievePort = QtWidgets.QLineEdit(self.groupBoxTankControl)
        self.lineEditRecievePort.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditRecievePort.sizePolicy().hasHeightForWidth())
        self.lineEditRecievePort.setSizePolicy(sizePolicy)
        self.lineEditRecievePort.setMinimumSize(QtCore.QSize(40, 20))
        self.lineEditRecievePort.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEditRecievePort.setMaxLength(5)
        self.lineEditRecievePort.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditRecievePort.setObjectName("lineEditRecievePort")
        self.gridLayout_4.addWidget(self.lineEditRecievePort, 3, 2, 1, 1)
        self.pushButtonStopCom = QtWidgets.QPushButton(self.groupBoxTankControl)
        self.pushButtonStopCom.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStopCom.sizePolicy().hasHeightForWidth())
        self.pushButtonStopCom.setSizePolicy(sizePolicy)
        self.pushButtonStopCom.setMinimumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonStopCom.setFont(font)
        self.pushButtonStopCom.setObjectName("pushButtonStopCom")
        self.gridLayout_4.addWidget(self.pushButtonStopCom, 4, 3, 1, 1)
        self.pushButtonStartCom = QtWidgets.QPushButton(self.groupBoxTankControl)
        self.pushButtonStartCom.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStartCom.sizePolicy().hasHeightForWidth())
        self.pushButtonStartCom.setSizePolicy(sizePolicy)
        self.pushButtonStartCom.setMinimumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonStartCom.setFont(font)
        self.pushButtonStartCom.setObjectName("pushButtonStartCom")
        self.gridLayout_4.addWidget(self.pushButtonStartCom, 3, 3, 1, 1)
        self.lineEditSendPortFOPIDContr = QtWidgets.QLineEdit(self.groupBoxTankControl)
        self.lineEditSendPortFOPIDContr.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSendPortFOPIDContr.sizePolicy().hasHeightForWidth())
        self.lineEditSendPortFOPIDContr.setSizePolicy(sizePolicy)
        self.lineEditSendPortFOPIDContr.setMinimumSize(QtCore.QSize(40, 20))
        self.lineEditSendPortFOPIDContr.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEditSendPortFOPIDContr.setMaxLength(5)
        self.lineEditSendPortFOPIDContr.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditSendPortFOPIDContr.setObjectName("lineEditSendPortFOPIDContr")
        self.gridLayout_4.addWidget(self.lineEditSendPortFOPIDContr, 1, 2, 1, 1)
        self.lineEditTankSimTime = QtWidgets.QLineEdit(self.groupBoxTankControl)
        self.lineEditTankSimTime.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditTankSimTime.sizePolicy().hasHeightForWidth())
        self.lineEditTankSimTime.setSizePolicy(sizePolicy)
        self.lineEditTankSimTime.setMinimumSize(QtCore.QSize(40, 20))
        self.lineEditTankSimTime.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEditTankSimTime.setFont(font)
        self.lineEditTankSimTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditTankSimTime.setDragEnabled(False)
        self.lineEditTankSimTime.setClearButtonEnabled(False)
        self.lineEditTankSimTime.setObjectName("lineEditTankSimTime")
        self.gridLayout_4.addWidget(self.lineEditTankSimTime, 2, 2, 1, 1)
        self.lineEditRecieveIP = QtWidgets.QLineEdit(self.groupBoxTankControl)
        self.lineEditRecieveIP.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditRecieveIP.sizePolicy().hasHeightForWidth())
        self.lineEditRecieveIP.setSizePolicy(sizePolicy)
        self.lineEditRecieveIP.setMinimumSize(QtCore.QSize(90, 20))
        self.lineEditRecieveIP.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEditRecieveIP.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditRecieveIP.setObjectName("lineEditRecieveIP")
        self.gridLayout_4.addWidget(self.lineEditRecieveIP, 3, 1, 1, 1)
        self.pushButtonExitServer = QtWidgets.QPushButton(self.groupBoxTankControl)
        self.pushButtonExitServer.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonExitServer.sizePolicy().hasHeightForWidth())
        self.pushButtonExitServer.setSizePolicy(sizePolicy)
        self.pushButtonExitServer.setMinimumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonExitServer.setFont(font)
        self.pushButtonExitServer.setObjectName("pushButtonExitServer")
        self.gridLayout_4.addWidget(self.pushButtonExitServer, 3, 4, 2, 1)
        self.labelControlServerLabel = QtWidgets.QLabel(self.groupBoxTankControl)
        self.labelControlServerLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelControlServerLabel.sizePolicy().hasHeightForWidth())
        self.labelControlServerLabel.setSizePolicy(sizePolicy)
        self.labelControlServerLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.labelControlServerLabel.setObjectName("labelControlServerLabel")
        self.gridLayout_4.addWidget(self.labelControlServerLabel, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBoxTankControl)
        self.label_17.setMinimumSize(QtCore.QSize(40, 0))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setLineWidth(1)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 2, 1, 2)
        self.lineEditSendIPFOPIDContr = QtWidgets.QLineEdit(self.groupBoxTankControl)
        self.lineEditSendIPFOPIDContr.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSendIPFOPIDContr.sizePolicy().hasHeightForWidth())
        self.lineEditSendIPFOPIDContr.setSizePolicy(sizePolicy)
        self.lineEditSendIPFOPIDContr.setMinimumSize(QtCore.QSize(90, 20))
        self.lineEditSendIPFOPIDContr.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEditSendIPFOPIDContr.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditSendIPFOPIDContr.setObjectName("lineEditSendIPFOPIDContr")
        self.gridLayout_4.addWidget(self.lineEditSendIPFOPIDContr, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.labelSending = QtWidgets.QLabel(self.groupBoxTankControl)
        self.labelSending.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSending.sizePolicy().hasHeightForWidth())
        self.labelSending.setSizePolicy(sizePolicy)
        self.labelSending.setMinimumSize(QtCore.QSize(0, 0))
        self.labelSending.setObjectName("labelSending")
        self.gridLayout_4.addWidget(self.labelSending, 4, 0, 1, 1)
        self.lineEditSendIP = QtWidgets.QLineEdit(self.groupBoxTankControl)
        self.lineEditSendIP.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSendIP.sizePolicy().hasHeightForWidth())
        self.lineEditSendIP.setSizePolicy(sizePolicy)
        self.lineEditSendIP.setMinimumSize(QtCore.QSize(90, 20))
        self.lineEditSendIP.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEditSendIP.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditSendIP.setObjectName("lineEditSendIP")
        self.gridLayout_4.addWidget(self.lineEditSendIP, 4, 1, 1, 1)
        self.labelRecieveing = QtWidgets.QLabel(self.groupBoxTankControl)
        self.labelRecieveing.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRecieveing.sizePolicy().hasHeightForWidth())
        self.labelRecieveing.setSizePolicy(sizePolicy)
        self.labelRecieveing.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelRecieveing.setFont(font)
        self.labelRecieveing.setObjectName("labelRecieveing")
        self.gridLayout_4.addWidget(self.labelRecieveing, 3, 0, 1, 1)
        self.pushButtonToServer = QtWidgets.QPushButton(self.groupBoxTankControl)
        self.pushButtonToServer.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonToServer.sizePolicy().hasHeightForWidth())
        self.pushButtonToServer.setSizePolicy(sizePolicy)
        self.pushButtonToServer.setMinimumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonToServer.setFont(font)
        self.pushButtonToServer.setObjectName("pushButtonToServer")
        self.gridLayout_4.addWidget(self.pushButtonToServer, 1, 4, 2, 1)
        self.lineEditSendPort = QtWidgets.QLineEdit(self.groupBoxTankControl)
        self.lineEditSendPort.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSendPort.sizePolicy().hasHeightForWidth())
        self.lineEditSendPort.setSizePolicy(sizePolicy)
        self.lineEditSendPort.setMinimumSize(QtCore.QSize(40, 20))
        self.lineEditSendPort.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEditSendPort.setMaxLength(5)
        self.lineEditSendPort.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditSendPort.setObjectName("lineEditSendPort")
        self.gridLayout_4.addWidget(self.lineEditSendPort, 4, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBoxTankControl)
        self.label_15.setMinimumSize(QtCore.QSize(90, 0))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 1, 1, 1)
        self.labelControlSimTim = QtWidgets.QLabel(self.groupBoxTankControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelControlSimTim.sizePolicy().hasHeightForWidth())
        self.labelControlSimTim.setSizePolicy(sizePolicy)
        self.labelControlSimTim.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelControlSimTim.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelControlSimTim.setObjectName("labelControlSimTim")
        self.gridLayout_4.addWidget(self.labelControlSimTim, 2, 0, 1, 1)
        self.pushButtonUpdateTime = QtWidgets.QPushButton(self.groupBoxTankControl)
        self.pushButtonUpdateTime.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonUpdateTime.sizePolicy().hasHeightForWidth())
        self.pushButtonUpdateTime.setSizePolicy(sizePolicy)
        self.pushButtonUpdateTime.setMinimumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonUpdateTime.setFont(font)
        self.pushButtonUpdateTime.setObjectName("pushButtonUpdateTime")
        self.gridLayout_4.addWidget(self.pushButtonUpdateTime, 2, 1, 1, 1)
        self.pushButtonTestControl = QtWidgets.QPushButton(self.groupBoxTankControl)
        self.pushButtonTestControl.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonTestControl.sizePolicy().hasHeightForWidth())
        self.pushButtonTestControl.setSizePolicy(sizePolicy)
        self.pushButtonTestControl.setMinimumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonTestControl.setFont(font)
        self.pushButtonTestControl.setObjectName("pushButtonTestControl")
        self.gridLayout_4.addWidget(self.pushButtonTestControl, 1, 3, 2, 1)
        self.verticalLayout_2.addWidget(self.groupBoxTankControl)
        FOPIDOPT.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FOPIDOPT)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 440, 21))
        self.menubar.setObjectName("menubar")
        FOPIDOPT.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FOPIDOPT)
        self.statusbar.setObjectName("statusbar")
        FOPIDOPT.setStatusBar(self.statusbar)

        self.retranslateUi(FOPIDOPT)
        QtCore.QMetaObject.connectSlotsByName(FOPIDOPT)

    def retranslateUi(self, FOPIDOPT):
        _translate = QtCore.QCoreApplication.translate
        FOPIDOPT.setWindowTitle(_translate("FOPIDOPT", "FO - FOPDT Plant Controller and Tunner"))
        self.groupBox_2.setTitle(_translate("FOPIDOPT", "Plant Model"))
        self.label_11.setText(_translate("FOPIDOPT", "<html><head/><body><p>Start (rad/s):10<span style=\" font-size:10pt; vertical-align:super;\">-x</span></p></body></html>"))
        self.label_21.setText(_translate("FOPIDOPT", "<html><head/><body><p>Stop (rad/s):10<span style=\" font-size:10pt; vertical-align:super;\">x</span></p></body></html>"))
        self.lineEdit_StartFreq.setText(_translate("FOPIDOPT", "-4"))
        self.lineEdit_StartFreq.setPlaceholderText(_translate("FOPIDOPT", "Start (int)"))
        self.lineEdit_StopFreq.setText(_translate("FOPIDOPT", "4"))
        self.lineEdit_StopFreq.setPlaceholderText(_translate("FOPIDOPT", "Stop (int)"))
        self.pushButtonAddData.setText(_translate("FOPIDOPT", "Add"))
        self.pushButtonEditData.setText(_translate("FOPIDOPT", "Edit"))
        self.pushButtonDeleteData.setText(_translate("FOPIDOPT", "Delete"))
        self.label_19.setText(_translate("FOPIDOPT", "Approximate as"))
        self.label_18.setText(_translate("FOPIDOPT", "FO - FOPDT"))
        self.label_10.setText(_translate("FOPIDOPT", "of Order:"))
        self.lineEditOrder.setText(_translate("FOPIDOPT", "5"))
        self.lineEditOrder.setPlaceholderText(_translate("FOPIDOPT", "(int)"))
        self.pushButtonTune.setText(_translate("FOPIDOPT", "Tune"))
        self.groupBoxFOPIDParams.setTitle(_translate("FOPIDOPT", "Fractional PID Controller Parameters"))
        self.label_3.setText(_translate("FOPIDOPT", "Kp:"))
        self.lineEdit_Ki.setText(_translate("FOPIDOPT", "1"))
        self.lineEditConstMinMu.setText(_translate("FOPIDOPT", "0.001"))
        self.lineEditConstMaxKi.setText(_translate("FOPIDOPT", "1000"))
        self.lineEditConstMinKp.setText(_translate("FOPIDOPT", "-1000"))
        self.label_5.setText(_translate("FOPIDOPT", "lam:"))
        self.label_6.setText(_translate("FOPIDOPT", "Kd:"))
        self.lineEditConstMaxKd.setText(_translate("FOPIDOPT", "1000"))
        self.lineEdit_Mu.setText(_translate("FOPIDOPT", "0.5"))
        self.label_7.setText(_translate("FOPIDOPT", "mu:"))
        self.label_4.setText(_translate("FOPIDOPT", "Ki:"))
        self.lineEditConstMaxlam.setText(_translate("FOPIDOPT", "5"))
        self.lineEditConstMinKd.setText(_translate("FOPIDOPT", "-1000"))
        self.lineEdit_Kd.setText(_translate("FOPIDOPT", "1"))
        self.label_2.setText(_translate("FOPIDOPT", "Max"))
        self.lineEdit_Kp.setText(_translate("FOPIDOPT", "1"))
        self.lineEditConstMinKi.setText(_translate("FOPIDOPT", "-1000"))
        self.lineEdit_Lam.setText(_translate("FOPIDOPT", "0.9"))
        self.lineEditConstMaxMu.setText(_translate("FOPIDOPT", "5"))
        self.lineEditConstMaxKp.setText(_translate("FOPIDOPT", "1000"))
        self.lineEditConstMinlam.setText(_translate("FOPIDOPT", "0.001"))
        self.label.setText(_translate("FOPIDOPT", "Min"))
        self.label_8.setText(_translate("FOPIDOPT", "Constraints"))
        self.label_22.setText(_translate("FOPIDOPT", "<html><head/><body><p>Tune Option</p></body></html>"))
        self.pushButtonSetParams.setText(_translate("FOPIDOPT", "Set"))
        self.label_9.setText(_translate("FOPIDOPT", "to"))
        self.lineEditParamsValue.setText(_translate("FOPIDOPT", "1.0"))
        self.lineEditParamsValue.setPlaceholderText(_translate("FOPIDOPT", "x"))
        self.label_20.setText(_translate("FOPIDOPT", "0.001 <= x <= 2"))
        self.groupBoxSimParams.setTitle(_translate("FOPIDOPT", "Simulation Parameters"))
        self.labelIter.setText(_translate("FOPIDOPT", "No. of Iteration: "))
        self.lineEditIter.setText(_translate("FOPIDOPT", "10"))
        self.lineEditIter.setPlaceholderText(_translate("FOPIDOPT", "Start (int)"))
        self.labelStep.setText(_translate("FOPIDOPT", "Step (1/Sample Rate):"))
        self.lineEditDt.setText(_translate("FOPIDOPT", "0.01"))
        self.lineEditDt.setPlaceholderText(_translate("FOPIDOPT", "Sample Rate (int)"))
        self.groupBoxGainPhaseMargin.setTitle(_translate("FOPIDOPT", "Gain and Phase Margin"))
        self.groupBox_8.setTitle(_translate("FOPIDOPT", "Gain margin[dB]"))
        self.lineEditGainMargin.setText(_translate("FOPIDOPT", "0.6"))
        self.checkBoxGainMargin.setText(_translate("FOPIDOPT", "Use"))
        self.groupBox_9.setTitle(_translate("FOPIDOPT", "Phase margin[deg]"))
        self.lineEditPhaseMargin.setText(_translate("FOPIDOPT", "95"))
        self.lineEditPhaseMargin.setPlaceholderText(_translate("FOPIDOPT", "1 <= x <= 359"))
        self.checkBoxPhaseMargin.setText(_translate("FOPIDOPT", "Use"))
        self.groupBoxTankControl.setTitle(_translate("FOPIDOPT", "Tank Control"))
        self.label_28.setText(_translate("FOPIDOPT", "Plant"))
        self.lineEditRecievePort.setText(_translate("FOPIDOPT", "5006"))
        self.pushButtonStopCom.setText(_translate("FOPIDOPT", "Stop"))
        self.pushButtonStartCom.setText(_translate("FOPIDOPT", "Start"))
        self.lineEditSendPortFOPIDContr.setText(_translate("FOPIDOPT", "5201"))
        self.lineEditTankSimTime.setText(_translate("FOPIDOPT", "300"))
        self.lineEditTankSimTime.setPlaceholderText(_translate("FOPIDOPT", "Sample Rate (int)"))
        self.lineEditRecieveIP.setText(_translate("FOPIDOPT", "127.0.0.1"))
        self.lineEditRecieveIP.setPlaceholderText(_translate("FOPIDOPT", "X.X.X.X"))
        self.pushButtonExitServer.setText(_translate("FOPIDOPT", "Exit"))
        self.labelControlServerLabel.setText(_translate("FOPIDOPT", "Control Server(Local): "))
        self.label_17.setText(_translate("FOPIDOPT", "Port"))
        self.lineEditSendIPFOPIDContr.setText(_translate("FOPIDOPT", "127.0.0.1"))
        self.lineEditSendIPFOPIDContr.setPlaceholderText(_translate("FOPIDOPT", "X.X.X.X"))
        self.labelSending.setText(_translate("FOPIDOPT", "Sending  To: "))
        self.lineEditSendIP.setText(_translate("FOPIDOPT", "127.0.0.1"))
        self.lineEditSendIP.setPlaceholderText(_translate("FOPIDOPT", "X.X.X.X"))
        self.labelRecieveing.setText(_translate("FOPIDOPT", "Receiving From: "))
        self.pushButtonToServer.setText(_translate("FOPIDOPT", "Update\n"
"FOPID\n"
"Params"))
        self.lineEditSendPort.setText(_translate("FOPIDOPT", "5005"))
        self.label_15.setText(_translate("FOPIDOPT", "IP Address"))
        self.labelControlSimTim.setText(_translate("FOPIDOPT", "Sim Time [s]:"))
        self.pushButtonUpdateTime.setText(_translate("FOPIDOPT", "Update TIme"))
        self.pushButtonTestControl.setText(_translate("FOPIDOPT", "Test\n"
"Controller"))

