# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\CompSys\4th Semeter THESIS\Code\fomcon\fotfviewergui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow_fotfviewer(object):
    def setupUi(self, MainWindow_fotfviewer):
        MainWindow_fotfviewer.setObjectName("MainWindow_fotfviewer")
        MainWindow_fotfviewer.resize(468, 517)
        self.centralwidget = QtWidgets.QWidget(MainWindow_fotfviewer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        # self.pushButtonRefreshList = QtWidgets.QPushButton(self.groupBox_4)
        # font = QtGui.QFont()
        # font.setPointSize(12)
        # font.setBold(False)
        # font.setWeight(50)
        # self.pushButtonRefreshList.setFont(font)
        # self.pushButtonRefreshList.setObjectName("pushButtonRefreshList")
        # self.gridLayout_5.addWidget(self.pushButtonRefreshList, 1, 0, 1, 1)
        self.pushButton_AddFotf = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.pushButton_AddFotf.setFont(font)
        self.pushButton_AddFotf.setObjectName("pushButton_AddFotf")
        self.gridLayout_5.addWidget(self.pushButton_AddFotf, 0, 0, 1, 1)
        self.pushButton_DeleteFOTF = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.pushButton_DeleteFOTF.setFont(font)
        self.pushButton_DeleteFOTF.setObjectName("pushButton_DeleteFOTF")
        self.gridLayout_5.addWidget(self.pushButton_DeleteFOTF, 0, 2, 1, 1)
        self.pushButton_EditFOTF = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.pushButton_EditFOTF.setFont(font)
        self.pushButton_EditFOTF.setObjectName("pushButton_EditFOTF")
        self.gridLayout_5.addWidget(self.pushButton_EditFOTF, 0, 1, 1, 1)
        self.comboBoxFOTF = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxFOTF.sizePolicy().hasHeightForWidth())
        self.comboBoxFOTF.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxFOTF.setFont(font)
        self.comboBoxFOTF.setObjectName("comboBoxFOTF")
        self.gridLayout_5.addWidget(self.comboBoxFOTF, 1, 1, 1, 2)
        self.pushButtonGetOustaloop = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.pushButtonGetOustaloop.setFont(font)
        self.pushButtonGetOustaloop.setObjectName("pushButtonGetOustaloop")
        self.gridLayout_5.addWidget(self.pushButtonGetOustaloop, 2, 2, 1, 1)
        self.pushButtonViewInConsole = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonViewInConsole.setFont(font)
        self.pushButtonViewInConsole.setObjectName("pushButtonViewInConsole")
        self.gridLayout_5.addWidget(self.pushButtonViewInConsole, 1, 0, 1, 1)
        self.pushButton_StabilityTest = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_StabilityTest.setFont(font)
        self.pushButton_StabilityTest.setObjectName("pushButton_StabilityTest")
        self.gridLayout_5.addWidget(self.pushButton_StabilityTest, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_Freq = QtWidgets.QGroupBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.groupBox_Freq.setFont(font)
        self.groupBox_Freq.setObjectName("groupBox_Freq")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_Freq)
        self.gridLayout.setObjectName("gridLayout")
        self.label_21 = QtWidgets.QLabel(self.groupBox_Freq)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_Freq)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 0, 0, 1, 1)
        self.pushButton_BodePlot = QtWidgets.QPushButton(self.groupBox_Freq)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_BodePlot.setFont(font)
        self.pushButton_BodePlot.setObjectName("pushButton_BodePlot")
        self.gridLayout.addWidget(self.pushButton_BodePlot, 2, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_Freq)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 2, 1, 1)
        self.lineEdit_HigherFreq = QtWidgets.QLineEdit(self.groupBox_Freq)
        self.lineEdit_HigherFreq.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_HigherFreq.setFont(font)
        self.lineEdit_HigherFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_HigherFreq.setObjectName("lineEdit_HigherFreq")
        self.gridLayout.addWidget(self.lineEdit_HigherFreq, 1, 1, 1, 1)
        self.lineEdit_FreqDataPoints = QtWidgets.QLineEdit(self.groupBox_Freq)
        self.lineEdit_FreqDataPoints.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_FreqDataPoints.setFont(font)
        self.lineEdit_FreqDataPoints.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_FreqDataPoints.setObjectName("lineEdit_FreqDataPoints")
        self.gridLayout.addWidget(self.lineEdit_FreqDataPoints, 1, 2, 1, 1)
        self.lineEdit_LowerFreq = QtWidgets.QLineEdit(self.groupBox_Freq)
        self.lineEdit_LowerFreq.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_LowerFreq.setFont(font)
        self.lineEdit_LowerFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_LowerFreq.setObjectName("lineEdit_LowerFreq")
        self.gridLayout.addWidget(self.lineEdit_LowerFreq, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_Freq)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 2, 0, 1, 1)
        self.lineEdit_StopTime = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_StopTime.sizePolicy().hasHeightForWidth())
        self.lineEdit_StopTime.setSizePolicy(sizePolicy)
        self.lineEdit_StopTime.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_StopTime.setFont(font)
        self.lineEdit_StopTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_StopTime.setObjectName("lineEdit_StopTime")
        self.gridLayout_2.addWidget(self.lineEdit_StopTime, 1, 2, 1, 1)
        self.comboBoxTimeDomainType = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxTimeDomainType.sizePolicy().hasHeightForWidth())
        self.comboBoxTimeDomainType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxTimeDomainType.setFont(font)
        self.comboBoxTimeDomainType.setEditable(False)
        self.comboBoxTimeDomainType.setCurrentText("")
        self.comboBoxTimeDomainType.setMaxVisibleItems(2)
        self.comboBoxTimeDomainType.setModelColumn(0)
        self.comboBoxTimeDomainType.setObjectName("comboBoxTimeDomainType")
        self.gridLayout_2.addWidget(self.comboBoxTimeDomainType, 2, 2, 1, 1)
        self.lineEdit_StartTime = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_StartTime.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_StartTime.setFont(font)
        self.lineEdit_StartTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_StartTime.setObjectName("lineEdit_StartTime")
        self.gridLayout_2.addWidget(self.lineEdit_StartTime, 1, 0, 1, 1)
        self.pushButtonSimulate = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSimulate.sizePolicy().hasHeightForWidth())
        self.pushButtonSimulate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonSimulate.setFont(font)
        self.pushButtonSimulate.setObjectName("pushButtonSimulate")
        self.gridLayout_2.addWidget(self.pushButtonSimulate, 3, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 1, 1, 1)
        self.lineEdit_StepTime = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_StepTime.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_StepTime.setFont(font)
        self.lineEdit_StepTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_StepTime.setObjectName("lineEdit_StepTime")
        self.gridLayout_2.addWidget(self.lineEdit_StepTime, 1, 1, 1, 1)
        self.lineEdit_inputTime = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_inputTime.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_inputTime.setFont(font)
        self.lineEdit_inputTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_inputTime.setObjectName("lineEdit_inputTime")
        self.gridLayout_2.addWidget(self.lineEdit_inputTime, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        MainWindow_fotfviewer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_fotfviewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 468, 21))
        self.menubar.setObjectName("menubar")
        MainWindow_fotfviewer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_fotfviewer)
        self.statusbar.setObjectName("statusbar")
        MainWindow_fotfviewer.setStatusBar(self.statusbar)
        self.label_21.setBuddy(self.lineEdit_HigherFreq)
        self.label_19.setBuddy(self.lineEdit_LowerFreq)
        self.label_20.setBuddy(self.lineEdit_FreqDataPoints)
        self.label_16.setBuddy(self.lineEdit_StartTime)
        self.label_22.setBuddy(self.lineEdit_inputTime)
        self.label_18.setBuddy(self.lineEdit_StopTime)
        self.label_17.setBuddy(self.lineEdit_StepTime)


        self.retranslateUi(MainWindow_fotfviewer)
        self.comboBoxTimeDomainType.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_fotfviewer)

    def retranslateUi(self, MainWindow_fotfviewer):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_fotfviewer.setWindowTitle(_translate("MainWindow_fotfviewer", "FOTF Viewer"))
        self.groupBox_4.setTitle(_translate("MainWindow_fotfviewer", "FO Transfer Functions"))
        # self.pushButtonRefreshList.setText(_translate("MainWindow_fotfviewer", "Refresh List"))
        self.pushButton_AddFotf.setText(_translate("MainWindow_fotfviewer", "Add"))
        self.pushButton_DeleteFOTF.setText(_translate("MainWindow_fotfviewer", "Delete"))
        self.pushButton_EditFOTF.setText(_translate("MainWindow_fotfviewer", "Edit"))
        self.pushButtonGetOustaloop.setText(_translate("MainWindow_fotfviewer", "Get Oustaloop Model"))
        self.pushButtonViewInConsole.setText(_translate("MainWindow_fotfviewer", "View in console"))
        self.pushButton_StabilityTest.setText(_translate("MainWindow_fotfviewer", "Stability test"))
        self.groupBox_3.setTitle(_translate("MainWindow_fotfviewer", "System Analysis"))
        self.groupBox_Freq.setTitle(_translate("MainWindow_fotfviewer", "Frequency Domain"))
        self.label_21.setText(_translate("MainWindow_fotfviewer", "freq exponent (int)"))
        self.label_19.setText(_translate("MainWindow_fotfviewer", "freq exponent (-int)"))
        self.pushButton_BodePlot.setText(_translate("MainWindow_fotfviewer", "Bode Plot"))
        self.label_20.setText(_translate("MainWindow_fotfviewer", "Data points (int):"))
        self.lineEdit_HigherFreq.setText(_translate("MainWindow_fotfviewer", "5"))
        self.lineEdit_FreqDataPoints.setText(_translate("MainWindow_fotfviewer", "1000"))
        self.lineEdit_LowerFreq.setText(_translate("MainWindow_fotfviewer", "-5"))
        self.groupBox.setTitle(_translate("MainWindow_fotfviewer", "Time Domain"))
        self.label_16.setText(_translate("MainWindow_fotfviewer", "Start (s):"))
        self.label_22.setText(_translate("MainWindow_fotfviewer", "Input:"))
        self.lineEdit_StopTime.setText(_translate("MainWindow_fotfviewer", "30"))
        self.lineEdit_StartTime.setText(_translate("MainWindow_fotfviewer", "0"))
        self.pushButtonSimulate.setText(_translate("MainWindow_fotfviewer", "Simulate"))
        self.label_18.setText(_translate("MainWindow_fotfviewer", "Stop (s):"))
        self.label_17.setText(_translate("MainWindow_fotfviewer", "Step (s):"))
        self.lineEdit_StepTime.setText(_translate("MainWindow_fotfviewer", "0.05"))
        self.lineEdit_inputTime.setText(_translate("MainWindow_fotfviewer", "1"))