# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\CompSys\4th Semeter THESIS\Code\fomcon\trimdatagui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TrimDataForm(object):
    def setupUi(self, TrimDataForm):
        TrimDataForm.setObjectName("TrimDataForm")
        TrimDataForm.setWindowModality(QtCore.Qt.WindowModal)
        TrimDataForm.resize(200, 196)
        TrimDataForm.setMinimumSize(QtCore.QSize(0, 0))
        TrimDataForm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        TrimDataForm.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(TrimDataForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(TrimDataForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEditNewName = QtWidgets.QLineEdit(TrimDataForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditNewName.sizePolicy().hasHeightForWidth())
        self.lineEditNewName.setSizePolicy(sizePolicy)
        self.lineEditNewName.setObjectName("lineEditNewName")
        self.verticalLayout.addWidget(self.lineEditNewName)
        self.label_4 = QtWidgets.QLabel(TrimDataForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEditT1 = QtWidgets.QLineEdit(TrimDataForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditT1.sizePolicy().hasHeightForWidth())
        self.lineEditT1.setSizePolicy(sizePolicy)
        self.lineEditT1.setText("")
        self.lineEditT1.setReadOnly(False)
        self.lineEditT1.setObjectName("lineEditT1")
        self.verticalLayout.addWidget(self.lineEditT1)
        self.label_5 = QtWidgets.QLabel(TrimDataForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.lineEditT2 = QtWidgets.QLineEdit(TrimDataForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditT2.sizePolicy().hasHeightForWidth())
        self.lineEditT2.setSizePolicy(sizePolicy)
        self.lineEditT2.setReadOnly(False)
        self.lineEditT2.setObjectName("lineEditT2")
        self.verticalLayout.addWidget(self.lineEditT2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonOK = QtWidgets.QPushButton(TrimDataForm)
        self.pushButtonOK.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonOK.setFont(font)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.horizontalLayout.addWidget(self.pushButtonOK)
        self.pushButtonCancel = QtWidgets.QPushButton(TrimDataForm)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonCancel.setFont(font)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(TrimDataForm)
        QtCore.QMetaObject.connectSlotsByName(TrimDataForm)

    def retranslateUi(self, TrimDataForm):
        _translate = QtCore.QCoreApplication.translate
        TrimDataForm.setWindowTitle(_translate("TrimDataForm", "Trim Data"))
        self.label.setText(_translate("TrimDataForm", "New Data Name: (e.g. Data_1):"))
        self.label_4.setText(_translate("TrimDataForm", "Start Time T1[s]:"))
        self.label_5.setText(_translate("TrimDataForm", "End Time T2[s]:"))
        self.pushButtonOK.setText(_translate("TrimDataForm", "OK"))
        self.pushButtonCancel.setText(_translate("TrimDataForm", "Cancel"))

